-- module for serializing and deserializing game state

local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"

local server_entity_mod = require(ServerScriptService.Server.entity)
local types = require(ReplicatedStorage.Shared.types)
local util = require(ReplicatedStorage.Shared.util)

type World = types.World
type Entity = types.Entity
type HexCell = types.HexCell
type Inventory = types.Inventory

type Context = {}

type Schema<T> = {
	serialize: (T, Context) -> any,
	deserialize: (any, Context) -> T,
	-- serialize_binary: ((T, Context) -> string)?,
	-- deserialize_binary: ((string, Context) -> T)?,
}

function enum(symbols: { string }): Schema<string>
	local symbol_map = {}

	for i, symbol in symbols do
		if symbol_map[symbol] then
			continue
		end
		symbol_map[symbol] = i
	end

	return {
		serialize = function(symbol, context): any
			return symbol_map[symbol] or symbol
		end,
		deserialize = function(symbol_id): any
			return symbols[tonumber(symbol_id) :: any] or symbol_id
		end,
	}
end

local all_symbols = enum {
	-- Entity symbols
	"type",
	"coordinates",
	"primary_coordinate",
	"id",
	"rotation",
	"health",
	"max_health",
	"current_recipe",
	"enabled",
	"should_output",
	"decay",
	"is_decaying",
	"decayable",
	"researches",
	"cost",
	"inventory",
	"cost_fulfilled",
	"autogenerated",
	"status",
	"is_destroyed",
	"build_time",
	"owner",
	"queued_decisions",
	"server_data",
	"always_visible",
	"requested_at",
	"can_deconstruct",

	-- ResearchState symbols
	"cost",
	"cost_is_paid",
	"time",
	"progress",
	"description",
	"name",
	"id",
	"icon",
	"coord",
	"status",
	"precondition",

	-- Portal symbols
	"group",
	"open",
	"steps",
	"open_time",
	"close_time",

	-- HexCell symbols
	"type",
	"entities",
	"coordinate",
	"owner",
	"portal",
	"influences",
	"server_data",
	"presence",
	"influences",
	"visibility",
	"contact",
	"full",
	"portal",

	-- World symbols
	"entities",
	"cells",
	"systems",
	"coalitions",
	"teams",
	"neutral_team",
	"spectator_team",
	"spectator_visibilities",
	"updates_buffer",
	"turn",
	"highest_turn",
	"turn_start_time",
	"turn_end_time",
	"skipped",
	"current_skips",
	"needed_skips",
	"speed_multiplier",
	"speed_base",

	-- Inventory symbols
	"filter",
	"homogeneous",
	"items",
	"capacity",

	-- TeamData
	"id",
	"name",
	"color",
	"players",
	"leader",
	"is_player_team",
	"is_spectator_team",
	"server_data",
	"creative",
	"visibility",
}

function struct<T>(object: { [string]: Schema<any> | any }): Schema<T>
	return {
		serialize = function(value, context)
			if value == nil then
				return
			end
			local serialized = {}
			for k, v in value do
				serialized[all_symbols.serialize(k, context)] = if object[k] then object[k].serialize(v, context) else v
			end
			return serialized
		end,
		deserialize = function(value, context)
			if value == nil then
				return
			end
			local deserialized = {}
			for k, v in value do
				local key = all_symbols.deserialize(k, context)
				deserialized[key] = if object[key] then object[key].deserialize(v, context) else v
			end
			for k, v in object do
				if not deserialized[k] then
					if v.deserialize(nil, context) then
						deserialized[k] = v.deserialize(nil, context)
					end
				end
			end
			return deserialized
		end,
	}
end

function map<T>(key_schema: Schema<string>, value_schema: Schema<T>): Schema<{ [string]: T }>
	return {
		serialize = function(value, context)
			local serialized = {}
			for k, v in value do
				serialized[key_schema.serialize(k, context)] = value_schema.serialize(v, context)
			end
			return serialized
		end,
		deserialize = function(value, context)
			if value == nil then
				return
			end
			local deserialized = {}
			for k, v in value do
				deserialized[key_schema.deserialize(k, context)] = value_schema.deserialize(v, context)
			end
			return deserialized
		end,
	}
end

local boolean = {
	serialize = function(v)
		return if v then 1 else 0
	end,
	deserialize = function(v)
		return v == 1
	end,
}
local number = {
	serialize = function(v)
		if v == math.huge then
			return "inf"
		elseif v == -math.huge then
			return "-inf"
		end
		return v
	end,
	deserialize = function(v)
		if v == "inf" then
			return math.huge
		elseif v == "-inf" then
			return -math.huge
		end
		return v
	end,
}

local identity = {
	serialize = function(v)
		return v
	end,
	deserialize = function(v)
		return v
	end,
}

local ignore = {
	serialize = function() end,
	deserialize = function() end,
}

function default<T>(schema: Schema<T>, default_value: T): Schema<T>
	return {
		serialize = function(v, context)
			if util.deep_equal(v, default_value) then
				return nil
			end
			return schema.serialize(v, context)
		end,
		deserialize = function(v, context)
			if v == nil then
				return default_value
			end
			return schema.deserialize(v, context)
		end,
	}
end

function optional<T>(schema: Schema<T>): Schema<T | nil>
	return {
		serialize = function(v, context)
			if v == nil then
				return nil
			end
			return schema.serialize(v, context)
		end,
		deserialize = function(v, context)
			if v == nil then
				return nil
			end
			return schema.deserialize(v, context)
		end,
	}
end

function aliased(scope)
	return {
		serialize = function(value, context)
			local alias = context.alias_scopes[scope]
			if not alias.map[value] then
				table.insert(alias.list, value)
				alias.map[value] = #alias.list
			end
			return alias.map[value]
		end,
		deserialize = function(value, context)
			return context.alias_scopes[scope].list[tonumber(value)]
		end,
	}
end

function aliasable(schema, scope)
	return {
		serialize = function(value, context)
			context.alias_scopes = context.alias_scopes or {}
			context.alias_scopes[scope] = context.alias_scopes[scope] or { list = {}, map = {} }

			local serialized_value = schema.serialize(value, context)
			return {
				value = serialized_value,
				aliases = context.alias_scopes[scope].list,
				scope = scope,
			}
		end,
		deserialize = function(value, context)
			local aliased_table = value.aliases
			context.alias_scopes = context.alias_scopes or {}
			context.alias_scopes[scope] = {
				list = aliased_table,
				map = {},
			}
			for i, v in aliased_table do
				context.alias_scopes[scope].map[v] = i
			end
			return schema.deserialize(value.value, context)
		end,
	}
end

local team_data = struct {
	server_data = struct {
		creative = default(identity, false),
		visibility = default(identity, "normal"),
	},
}

local entity_id = aliased "entity_id"
local entity_types = enum(util.table_keys(server_entity_mod.registry))
local entity_server_data = struct {}

local statuses = enum {
	"blueprint",
	"scaffold",
	"complete",
}
local item_type = enum {
	"bar",
	"tar",
	"rad",
	"vit",
	"tek",
	"pow",
	"dye",
	"goo",
	"zap",
}

local inventory_schema: Schema<Inventory> = struct {
	items = map(identity, item_type),
}

local entity_schema: Schema<Entity> = struct {
	type = entity_types,
	id = entity_id,
	status = statuses,
	server_data = entity_server_data,
	health = default(number, 0),
	max_health = default(number, 0),
	inventory = optional(inventory_schema),
	decay = default(number, 0),
	is_destroyed = default(boolean, false),
	rotation = default(number, 0),
	cost = default(identity, {}),
	cost_fulfilled = default(identity, {}),
	build_time = default(number, 0),
}

local cell_types = enum {
	"basic",
	"portal",
	"bar_deposit",
	"tar_deposit",
	"rad_deposit",
	"vit_deposit",
}

local cell_schema = struct {
	type = default(cell_types, "basic"),
	server_data = ignore,
	entities = default(map(identity, entity_id), {}),
}

local world_schema = aliasable(
	struct {
		entities = map(entity_id, entity_schema),
		cells = map(identity, cell_schema),
		teams = map(identity, team_data),
		systems = ignore,
		turn_schedule = ignore,
		cell_instance_map = ignore,
		skipped = ignore,
		cell_instance_root = ignore,
		entity_instance_map = ignore,
		entity_instance_root = ignore,
		instance_entity_map = ignore,
		instance_cell_map = ignore,
		get_cell = ignore,
		new_team = ignore,
		purge_dead_entities = ignore,
		updates_buffer = ignore,
		world_update_signal = ignore,
		query_entity = ignore,
	},
	"entity_id"
)

function compress_world(world: World)
	return game:GetService("HttpService"):JSONEncode(world_schema.serialize(world, {}))
end

function decompress_world(state: string)
	return world_schema.deserialize(game:GetService("HttpService"):JSONDecode(state), {})
end

return {
	compress_world = compress_world,
	decompress_world = decompress_world,
}
