local ReplicatedStorage = game:GetService "ReplicatedStorage"
local types = require(ReplicatedStorage.Shared.types)
local util = require(ReplicatedStorage.Shared.util)
local shared_entity_mod = require(ReplicatedStorage.Shared.entity)
local coords = require(ReplicatedStorage.Shared.coords)

local server_util = require(script.Parent.util)
local server_types = require(script.Parent.types)
local updates_mod = require(script.Parent.updates)

type Damage = types.Damage
type HexCell = types.HexCell
type World = types.World
type PartialWorld = types.PartialWorld
type Entity = types.Entity
type ActionState = server_types.ActionState
type CellType = types.CellType
type TeamId = types.TeamId
type CubicCoordinate = types.CubicCoordinate
type DamageResult = server_types.DamageResult
type EntityEvent = types.EntityEvent

export type ServerEntityBehavior = {
	autogenerates_vertex: boolean?,
	decayable: boolean,
	type: string,

	abilities: { [string]: (self: Entity, world: World) -> () },
	built_on: { CellType },

	illuminates: (self: Entity, world: World) -> { CubicCoordinate },
	influences: ((self: Entity, world: World) -> ())?,
	init: (self: Entity, world: World) -> (),
	on_completed: (self: Entity, world: World) -> (),
	on_event: (self: Entity, world: World, event: EntityEvent, action_state: ActionState) -> (),
	-- laboratory only
	on_research_completed: (self: Entity, world: World, research_id: string) -> ()?,

	--- called at the start of every action phase
	tick: (self: Entity, world: World, action_state: ActionState?) -> (),
}

local registry: { [string]: ServerEntityBehavior } = {}

local noop = function() end

function with_defaults(behavior: any): ServerEntityBehavior
	behavior.init = behavior.init or noop
	behavior.tick = behavior.tick or noop
	if behavior.decayable == nil then
		behavior.decayable = true
	end
	behavior.on_completed = behavior.on_completed or noop
	behavior.built_on = behavior.built_on or {}
	behavior.influences = behavior.influences or noop
	behavior.on_event = behavior.on_event or noop
	behavior.abilities = behavior.abilities or {}
	behavior.illuminates = function(self, world)
		return {}
	end
	return behavior
end

function entity_can_deconstruct(entity: Entity, world: World)
	local cell = world:get_cell(entity.primary_coordinate)
	assert(cell, "cell not found")
	if
		entity.type == "vertex"
		and not util.table_any(cell.entities, function(_, entity_id)
			return shared_entity_mod.registry[world.entities[entity_id].type].layer > shared_entity_mod.LAYER.vertex
		end)
	then
		return false
	end
	return true
end

function autogenerate_vertex(world: World, host: Entity)
	if #world:query_entity { coordinate = host.primary_coordinate, type = "vertex", owner = host.owner } == 0 then
		-- the status is the highest status among buildings that come with vertex
		-- principally used when buildings spawn in already completed, and the vertex that come with must also be completed
		local status = "blueprint"
		for _, entity in world:query_entity { coordinate = host.primary_coordinate, owner = host.owner } do
			if registry[entity.type].autogenerates_vertex then
				if (status == "blueprint" or status == "scaffold") and entity.status == "complete" then
					status = "complete"
				elseif status == "blueprint" and entity.status == "scaffold" then
					status = "scaffold"
				end
			end
		end
		local _vertex = new_entity({
			type = "vertex",
			primary_coordinate = host.primary_coordinate,
			status = status,
			build_time = -1,
			can_deconstruct = false,
			autogenerated = status == "blueprint" and true,
			owner = host.owner,
			decayable = host.decayable,
			cost = {},
		}, world)
	end
end

--- Creates a new entity on a world
--- And adds relevant events to the updates buffer
function new_entity(entity_: any, world: World): Entity
	local entity = entity_ :: Entity
	if not world then
		error "argument 2 not provided"
	end
	local server_behavior = registry[entity.type]
	local shared_behavior = shared_entity_mod.registry[entity.type]
	local cell
	if entity.primary_coordinate then
		cell = world:get_cell(entity.primary_coordinate)
		if not cell then
			error("No cell at " .. coords.encode_coord(entity.primary_coordinate))
		end
	else
		warn "no primary_coordinate provided"
	end
	if server_behavior == nil then
		error("No server behavior for " .. entity.type)
	end
	if shared_behavior == nil then
		error("No shared behavior for " .. entity.type)
	end

	-- quickly catch when i use TeamData for owner instead of TeamId
	assert(not entity.owner or typeof(entity.owner) == "number", "Entity owner is not a number")

	local defaults = {
		active = true,
		build_time = shared_behavior.build_time,
		coordinates = { entity.primary_coordinate },
		cost = shared_behavior.cost,
		cost_fulfilled = {},
		decay = 0,
		decayable = server_behavior.decayable,
		effects = {},
		enabled = true,
		health = shared_behavior.max_health,
		id = server_util.new_global_id(),
		is_destroyed = false,
		max_health = shared_behavior.max_health,
		name = shared_behavior.name,
		owner = world.neutral_team,
		queued_decisions = {},
		server_data = {},
		rotation = 0,
		status = "complete",
	}
	for k, v in defaults do
		if entity[k] == nil then
			entity[k] = v
		end
	end
	entity.server_data.requested_at = if entity.server_data.requested_at ~= nil
		then entity.server_data.requested_at
		else os.clock()

	entity.server_data.always_visible_for = if entity.server_data.always_visible_for ~= nil
		then entity.server_data.always_visible_for
		else {}

	-- todo: rotate the offsets by the rotation
	for _, offset in shared_behavior.offsets do
		table.insert(entity.coordinates, coords.coords_add(entity.primary_coordinate, offset))
	end

	server_behavior.init(entity, world)
	world.entities[entity.id] = entity
	if cell then
		cell.entities[entity.id] = true
	end

	if entity.status == "complete" then
		server_behavior.on_completed(entity, world)
	end
	if server_behavior.autogenerates_vertex and entity.owner ~= world.neutral_team then
		autogenerate_vertex(world, entity)
	end

	updates_mod.add_update(world, { type = "entity_update", entity = entity })
	updates_mod.add_update(world, {
		type = "entity_created",
		entity_id = entity.id,
	})
	return entity
end

-- Marks an entity as destroyed, removing it from the cells it occupies
-- Does not remove it from world.entities
function remove_entity(world: World, entity: Entity)
	local cell = world:get_cell(entity.primary_coordinate)
	assert(cell, "cell not found")
	for _, coord in entity.coordinates do
		cell.entities[entity.id] = nil
	end
	entity.is_destroyed = true
	updates_mod.add_update(world, { type = "entity_update", entity = entity })
	table.insert(world.action_queue, {
		event_type = "entity_event",
		type = "removed",
		entity_id = entity.id,
	})
end

-- todo: make this respect rotation
function move_entity(world: World, entity: Entity, new_coordinate: CubicCoordinate, rotation: number?)
	for _, coord in entity.coordinates do
		local cell = world:get_cell(coord)
		assert(cell, "cell not found")
		cell.entities[entity.id] = nil
	end

	local shared_entity_behavior = shared_entity_mod.registry[entity.type]
	entity.primary_coordinate = new_coordinate

	for _, coord in shared_entity_behavior.offsets do
		table.insert(entity.coordinates, coords.coords_add(new_coordinate, coord))
	end

	for _, coord in entity.coordinates do
		local cell = world:get_cell(coord)
		assert(cell, "cell not found")
		cell.entities[entity.id] = true
	end
end

return {
	remove_entity = remove_entity,
	autogenerates_vertex = autogenerate_vertex,
	new_entity = new_entity,
	with_defaults = with_defaults,
	entity_can_deconstruct = entity_can_deconstruct,
	registry = registry,
}
