local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"
local types = require(ReplicatedStorage.Shared.types)
local util = require(ReplicatedStorage.Shared.util)
local remotes_mod = require(ServerScriptService.Server.remotes)
local shared_registry_mod = require(ReplicatedStorage.Shared.entity.registry)
local hex_grid_mod = require(ReplicatedStorage.Shared.hex_grid)
local registry = require(script.Parent.registry).registry
local server_util = require(ServerScriptService.Server.util)
local server_types = require(ServerScriptService.Server.types)

type HexGrid = types.HexGrid
type Entity = types.Entity
type CubicCoordinate = types.CubicCoordinate
type ActionState = server_types.ActionState
type GridUpdate = types.GridUpdate

function entity_can_deconstruct(entity: Entity, grid: HexGrid)
	if
		entity.type == "wires"
		and not util.table_any(grid:get_cell(entity.primary_coordinate).entities, function(entity_id)
			return shared_registry_mod.registry[grid.entities[entity_id].type].layer > shared_registry_mod.layer.wire
		end)
	then
		return false
	end
	return true
end
function trigger_neighbors(grid: HexGrid, origin: CubicCoordinate, action_state: ActionState?)
	for _, coord in hex_grid_mod.neighbors_leq(origin, 1) do
		local cell = grid:get_cell(coord)
		if not cell then
			continue
		end
		for _, entity_id in cell.entities do
			local neighbor_entity = grid.entities[entity_id]
			registry[neighbor_entity.type].neighbor_changed(neighbor_entity, grid, action_state)
		end
	end
end
function autogenerate_wires(grid: HexGrid, host: Entity, action_state: ActionState?)
	if #grid:query_entity { primary_coordinate = host.primary_coordinate, type = "wires", owner = host.owner } == 0 then
		-- the status is the highest status among buildings that come with wires
		local status = "blueprint"
		for _, entity in grid:query_entity { primary_coordinate = host.primary_coordinate, owner = host.owner } do
			if registry[entity.type].autogenerate_wires then
				if (status == "blueprint" or status == "scaffold") and entity.status == "complete" then
					status = "complete"
				elseif status == "blueprint" and entity.status == "scaffold" then
					status = "scaffold"
				end
			end
		end
		local entity = new_entity({
			type = "wires",
			primary_coordinate = host.primary_coordinate,
			status = status,
			build_time = -1,
			can_deconstruct = false,
			autogenerated = status == "blueprint" and true,
			owner = host.owner,
			decayable = host.decayable,
			cost = {},
		}, grid, action_state)
	end
end

-- Creates a new entity on a grid
-- And adds relevant events to the updates buffer
function new_entity(entity: table, grid: HexGrid, action_state: ActionState?): Entity
	if not grid then
		error "argument 2 not provided"
	end
	local server_behavior = registry[entity.type]
	local shared_behavior = shared_registry_mod.registry[entity.type]
	local cell = grid:get_cell(entity.primary_coordinate)
	if not cell then
		error("No cell at " .. hex_grid_mod.encode_coord(entity.primary_coordinate))
	end
	if server_behavior == nil then
		error("No server behavior for " .. entity.type)
	end
	if shared_behavior == nil then
		error("No shared behavior for " .. entity.type)
	end
	entity.id = entity.id or server_util.new_global_id()
	entity.name = entity.name or shared_registry_mod.registry[entity.type].name
	entity.queued_decisions = entity.queued_decisions or {}
	entity.rotation = if entity.rotation ~= nil then entity.rotation else 0
	entity.health = entity.health or shared_behavior.max_health
	entity.status = entity.status or "blueprint"
	entity.max_health = shared_behavior.max_health
	entity.enabled = if entity.enabled ~= nil then entity.enabled else true
	entity.decay = entity.decay or 0
	entity.decayable = if entity.decayable ~= nil then entity.decayable else true
	entity.build_time = entity.build_time or shared_behavior.build_time
	entity.coordinates = entity.coordinates or { entity.primary_coordinate }
	entity.cost = entity.cost or shared_behavior.cost
	entity.is_destroyed = entity.is_destroyed or false
	entity.cost_fulfilled = entity.cost_fulfilled or {}
	-- quickly catch when i use TeamData for owner instead of TeamId
	assert(not entity.owner or typeof(entity.owner) == "number", "Entity owner is not a number")
	entity.owner = entity.owner or grid.neutral_team
	entity.server_data = entity.server_data or {}
	entity.server_data.requested_at = entity.server_data.requested_at or DateTime.now().UnixTimestampMillis

	-- todo: rotate the offsets by the rotation
	for _, offset in shared_behavior.offsets do
		table.insert(entity.coordinates, hex_grid_mod.coords_add(entity.primary_coordinate, offset))
	end

	server_behavior.init(entity, grid)
	grid.entities[entity.id] = entity
	table.insert(cell.entities, entity.id)

	if entity.status == "complete" then
		server_behavior.on_completed(entity, grid)
	end
	if server_behavior.autogenerate_wires then
		autogenerate_wires(grid, entity, action_state)
	end

	if action_state then
		action_state.dirty_entities[entity.id] = action_state.dirty_entities[entity.id] or {}
		action_state.dirty_entities[entity.id].everyone = true
	end
	table.insert(grid.updates_buffer[#grid.updates_buffer], { type = "entity_update", entity = entity })
	table.insert(grid.updates_buffer[#grid.updates_buffer], {
		type = "entity_created",
		entity_id = entity.id,
	})
	return entity
end

-- Marks an entity as destroyed, removing it from the cells it occupies
-- Does not remove it from grid.entities
function remove_entity(grid: HexGrid, entity: Entity, action_state: ActionState?)
	for _, coord in entity.coordinates do
		util.table_remove_needle(grid:get_cell(coord).entities, entity.id)
	end
	entity.is_destroyed = true
	table.insert(grid.updates_buffer[#grid.updates_buffer], { type = "entity_update", entity = entity })
	table.insert(grid.updates_buffer[#grid.updates_buffer], {
		type = "entity_destroyed",
		entity_id = entity.id,
	})
	if action_state then
		action_state.dirty_entities[entity.id] = action_state.dirty_entities[entity.id] or {}
		action_state.dirty_entities[entity.id].everyone = true
	end
end

return {
	remove_entity = remove_entity,
	autogenerate_wires = autogenerate_wires,
	new_entity = new_entity,
	trigger_neighbors = trigger_neighbors,
}
