local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"
local types = require(ReplicatedStorage.Shared.types)
local server_types = require(ServerScriptService.Server.types)
local server_util = require(ServerScriptService.Server.util)
local util = require(ReplicatedStorage.Shared.util)
local registry_mod = require(script.Parent.registry)
local methods = require(script.Parent.methods)
local registry = registry_mod.registry
local with_defaults = registry_mod.with_defaults
local updates_mod = require(ServerScriptService.Server.updates)

type Entity = types.Entity
type EntityId = types.EntityId
type HexCell = types.HexCell
type CubicCoordinate = types.CubicCoordinate
type HexGrid = types.HexGrid
type ActionState = server_types.ActionState

registry.vertex = with_defaults {
	neighbor_changed = function(self: Entity, grid: HexGrid)
		local cell = grid:get_cell(self.primary_coordinate)
		assert(cell, "cell not found")
		if self.autogenerated then
			if
				not util.table_any(cell.entities, function(_, id)
					return registry[grid.entities[id].type].autogenerates_vertex
				end)
			then
				methods.remove_entity(grid, self)
			end
		end
	end,
	on_completed = function(self: Entity, grid: HexGrid)
		-- Capturing mechanics: if this entity is not neutral, and is built on a cell that has neutral entities,
		-- neutral entities are captured, neutral vertex are destroyed
		if self.owner == grid.neutral_team then
			return
		end
		local cell = grid:get_cell(self.primary_coordinate)
		for entity_id in cell.entities do
			local entity = grid.entities[entity_id]
			if entity.owner == grid.neutral_team then
				if entity.type == "vertex" then
					methods.remove_entity(grid, entity)
				else
					entity.owner = self.owner
				end
				updates_mod.add_update(grid, { type = "entity_update", entity = entity })
			end
		end
	end,
}

return {}
