local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"
local types = require(ReplicatedStorage.Shared.types)
local server_types = require(ServerScriptService.Server.types)
local server_util = require(ServerScriptService.Server.util)
local util = require(ReplicatedStorage.Shared.util)
local registry_mod = require(script.Parent.registry)
local methods = require(script.Parent.methods)
local registry = registry_mod.registry
local with_defaults = registry_mod.with_defaults

type Entity = types.Entity
type EntityId = types.EntityId
type HexCell = types.HexCell
type CubicCoordinate = types.CubicCoordinate
type HexGrid = types.HexGrid
type ActionState = server_types.ActionState

registry["wires"] = with_defaults {
	neighbor_changed = function(self: Entity, grid: HexGrid, action_state: ActionState?)
		local cell = grid:get_cell(self.primary_coordinate)
		assert(cell, "cell not found")
		if self.autogenerated then
			if
				not util.table_any(cell.entities, function(id)
					return registry[grid.entities[id].type].autogenerate_wires
				end)
			then
				methods.remove_entity(grid, self, action_state)
			end
		end
	end,
	on_completed = function(self: Entity, grid: HexGrid, action_state: ActionState?)
		-- Capturing mechanics: if this entity is not neutral, and is built on a cell that has neutral entities,
		-- neutral entities are captured, neutral wires are destroyed
		if self.owner ~= grid.neutral_team then
			local cell = grid:get_cell(self.primary_coordinate)
			for _, entity_id in cell.entities do
				local entity = grid.entities[entity_id]
				if entity.owner == grid.neutral_team then
					if entity.type == "wires" then
						methods.remove_entity(grid, entity, action_state)
					else
						entity.owner = self.owner
					end
					if action_state then
						server_util.mark_dirty_for_everyone(action_state, entity_id)
					end
				end
			end
		end
	end,
}

return {}
