local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"
local types = require(ReplicatedStorage.Shared.types)
local registry_mod = require(script.Parent.registry)
local registry = registry_mod.registry
local with_defaults = registry_mod.with_defaults
local util = require(ReplicatedStorage.Shared.util)
local methods = require(script.Parent.methods)
local server_types = require(ServerScriptService.Server.types)

type Entity = types.Entity
type EntityId = types.EntityId
type HexCell = types.HexCell
type CubicCoordinate = types.CubicCoordinate
type HexGrid = types.HexGrid
type ActionState = server_types.ActionState

registry["wires"] = with_defaults {
	neighbor_changed = function(self: Entity, grid: HexGrid, action_state: ActionState?)
		if self.autogenerated then
			if
				not util.table_any(grid:get_cell(self.primary_coordinate).entities, function(id)
					return registry[grid.entities[id].type].autogenerate_wires
				end)
			then
				methods.remove_entity(grid, self, action_state)
			end
		end
	end,
	on_completed = function(self: Entity, grid: HexGrid, action_state: ActionState?)
		-- Capturing mechanics: if this entity is not neutral, and is built on a cell that has neutral entities,
		-- neutral entities are captured, neutral wires are destroyed
		if self.owner ~= grid.neutral_team then
			local cell = grid:get_cell(self.primary_coordinate)
			for _, entity_id in cell.entities do
				local entity = grid.entities[entity_id]
				if entity.owner == grid.neutral_team then
					if entity.type == "wires" then
						methods.remove_entity(grid, entity, action_state)
					else
						entity.owner = self.owner
					end
					if action_state then
						action_state.dirty_entities[entity_id] = action_state.dirty_entities[entity_id] or {}
						action_state.dirty_entities[entity_id].everyone = true
					end
				end
			end
		end
	end,
}

return {}
