local ReplicatedStorage = game:GetService "ReplicatedStorage"
local types = require(ReplicatedStorage.Shared.types)
local util = require(ReplicatedStorage.Shared.util)
local world_mod = require(ReplicatedStorage.Shared.world)
local items_mod = require(ReplicatedStorage.Shared.items)
local team_mod = require(ReplicatedStorage.Shared.team)
local result = require(ReplicatedStorage.Shared.result)
local researches = require(ReplicatedStorage.Shared.researches)

local questing = require(script.Parent.questing)
local turn_scheduler = require(script.Parent.turn_scheduler)
local server_entity_mod = require(script.Parent.entity)
local updates_mod = require(script.Parent.updates)
local server_types = require(script.Parent.types)
local entity_mod = require(script.Parent.entity)
local structures = require(script.Parent.structures)

local ability_interaction = require(script.ability_interaction).ability_interaction
local construct_interaction = require(script.construct_interaction).construct_interaction

type World = types.World
type Interaction = types.Interaction
type TeamData = types.TeamData
type Entity = types.Entity
type WorldUpdate = types.WorldUpdate
type TeamId = types.TeamId
type PlayerInfo = server_types.PlayerInfo
type EntityId = types.EntityId

-- remove autogenerated vertices if the entity that generated them got removed
function remove_unsupported_vertices(world: World, entity: Entity)
	if entity.status == "blueprint" then
		for _, coord in entity.coordinates do
			local vertices = world:query_entity {
				coordinate = coord,
				type = "vertex",
				status = "blueprint",
				autogenerated = true,
			}

			if #vertices == 0 then
				continue
			end
			local supported = false
			for _, other_blueprint in
				world:query_entity {
					coordinate = coord,
					status = "blueprint",
				}
			do
				local behavior = server_entity_mod.registry[other_blueprint.type]
				if behavior.autogenerates_vertex then
					supported = true
					break
				end
			end
			if not supported then
				for _, vertex in vertices do
					world:add_update {
						type = "entity_event",
						event_type = "destroy",
						entity_id = vertex.id,
						death_type = "other",
					}
					entity_mod.remove_entity(world, vertex)
				end
			end
		end
	end
end

function handle_interaction(world: World, entry: Interaction, player_info: PlayerInfo): { [EntityId]: boolean }
	if typeof(entry) ~= "table" then
		error "Expected entry to be a table"
	end
	if entry.type == "construct" then
		return construct_interaction(world, entry, player_info)
	elseif entry.type == "ability" then
		return ability_interaction(world, entry, player_info)
	elseif entry.type == "rotate_entity" then
		local entity = world.entities[entry.entity_id]
		if not entity or not entity.active or entity.owner ~= player_info.team then
			-- error_type.mistake
			return {}
		end
		entity.rotation = entry.rotation
		return { [entity.id] = true }
	elseif entry.type == "cancel_decision" then
		local entity = world.entities[entry.entity_id]
		if not entity or not entity.active or entity.owner ~= player_info.team then
			-- error_type.mistake
			return {}
		end
		util.table_extract(entity.queued_decisions, function(decision)
			if entry.ability_id then
				return decision.type == entry.decision_type and decision.ability_id == entry.ability_id
			else
				return decision.type == entry.decision_type
			end
		end)
		return { [entity.id] = true }
	elseif entry.type == "add_research" then
		local entity = world.entities[entry.entity_id]
		if
			not entity
			or not entity.active
			or entity.owner ~= player_info.team
			or entity.status ~= "complete"
			or entity.researches == nil
			or not entity.researches.states[entry.research_id]
		then
			-- error_type.mistake
			return {}
		end
		-- check that this research is not already in queue
		if
			util.table_find_pred(entity.researches.queue, function(research)
				return research == entry.research_id
			end)
		then
			-- error_type.dismiss
			return {}
		end

		local research_item = entity.researches.states[entry.research_id]
		if
			research_item.status ~= "incomplete"
			or not researches.research_is_available(research_item, entity.researches)
		then
			return {}
		end

		research_item.status = "researching"
		table.insert(entity.researches.queue, entry.research_id)
		return { [entity.id] = true }
	elseif entry.type == "remove_research" then
		local entity = world.entities[entry.entity_id]

		if
			not entity
			or not entity.active
			or entity.owner ~= player_info.team
			or entity.status ~= "complete"
			or entity.researches == nil
			or not entity.researches.states[entry.research_id]
		then
			-- error_type.mistake
			return {}
		end

		local idx = table.find(entity.researches.queue, entry.research_id)
		if not idx then
			return {}
		end
		-- remove all researches at and after idx
		for i = idx, #entity.researches.queue do
			entity.researches.states[entity.researches.queue[i]].status = "incomplete"
			entity.researches.queue[i] = nil
		end
		return { [entity.id] = true }
	elseif entry.type == "deconstruct" then
		local entity = world.entities[entry.entity_id]
		if not entity or not entity.active or entity.owner ~= player_info.team then
			-- error_type.mistake
			return {}
		end
		if
			util.table_find_pred(entity.queued_decisions, function(action)
				return action.type == "deconstruct"
			end)
		then
			return {}
		end
		if entity.status == "complete" or entity.status == "scaffold" then
			table.insert(entity.queued_decisions, entry)
			updates_mod.flush_updates(world)
			return { [entity.id] = true }
		else
			world:add_update {
				type = "entity_event",
				event_type = "destroy",
				entity_id = entity.id,
				death_type = "deconstruct",
			}
			entity_mod.remove_entity(world, entity)
			remove_unsupported_vertices(world, entity)
			return {}
		end
	elseif entry.type == "set_entity_enabled" then
		local entity = world.entities[entry.entity_id]
		if not entity or not entity.active or entity.owner ~= player_info.team or entity.status ~= "complete" then
			-- error_type.mistake
			return {}
		end

		entity.enabled = not not entry.enabled
		return { [entity.id] = true }
	elseif entry.type == "set_recipe" then
		local entity = world.entities[entry.entity_id]
		if not entity or not entity.active or entity.owner ~= player_info.team or entity.status ~= "complete" then
			-- error_type.mistake
			return {}
		end
		entity.current_recipe = entry.recipe_id
		return { [entity.id] = true }
	elseif entry.type == "set_inventory_filter" then
		local entity = world.entities[entry.entity_id]
		if
			not entity
			or not entity.active
			or entity.owner ~= player_info.team
			or entity.status ~= "complete"
			or entity.inventory == nil
		then
			return {}
		end

		entity.inventory.filter = {
			type = "blacklist",
			items = {},
		}

		if entry.filter.type == "whitelist" then
			entity.inventory.filter.type = "whitelist"
		end

		for item, value in entry.filter.items do
			if value == true and items_mod.item_names[item] ~= nil then
				entity.inventory.filter.items[item] = true
			end
		end

		return { [entity.id] = true }
	elseif entry.type == "skip" then
		assert(player_info.player, "no player")
		local team = team_mod.team_of(world, player_info.player)
		if not team.is_player_team then
			return {}
		end
		if table.find(world.skipped, player_info.player.UserId) == nil then
			table.insert(world.skipped, player_info.player.UserId)
			if world.turn_schedule then
				turn_scheduler.recalculate_skips(world)
			end
		end
		return {}
	elseif entry.type == "quest_advance" then
		local quest = world.quests[entry.quest_id]
		if quest and quest.stages_data[quest.current_stage] and quest.stages_data[quest.current_stage].can_advance then
			questing.quest_advance(world.quests[entry.quest_id], world)
		end
		return {}
	elseif entry.type == "quest_select_choice" then
		local quest = world.quests[entry.quest_id]
		if quest then
			questing.quest_select_choice(quest, world, entry.choice_id)
		end
		return {}
	elseif entry.type == "tutorial_report_selection" then
		local tutorial = world.quests.tutorial
		if tutorial then
			(tutorial.tutorial_player_selection :: any)[player_info.player] = entry.selected
			questing.quest_update(tutorial, world)
		end
		return {}
	elseif entry.type == "update_settings" then
		if player_info.player == nil then
			error "no player"
		end
		local player_data = world.player_data[tostring(player_info.player.UserId)]
		local res = structures.player_settings.validate(entry.settings)
		local player_settings = result.unwrap(res)
		player_data.settings = player_settings
		world:add_update {
			type = "player_data",
			player_data = {
				[tostring(player_info.player.UserId)] = player_data,
			},
		}
		return {}
	else
		error("unknown interaction type: " .. entry.type)
	end
end

function on_client_interaction(
	world: World,
	props: { player_team: TeamData, data: { Interaction }, plr: Player? }
): {
	error_type: number,
	updates: { [TeamId]: WorldUpdate },
}
	local player_info = {
		team = props.player_team.id,
		player = props.plr,
	}
	local data = props.data
	if typeof(data) ~= "table" then
		error "Expected data to be a table"
	end

	local dirty_entities = {}

	if #data == 0 and next(data) ~= nil then
		error "Expected data to be an array"
	end
	local t = os.clock()
	for _, entry in data do
		t += 0.001
		entry.requested_at = t
		local dirty = handle_interaction(world, entry, player_info)
		for entity_id in dirty do
			dirty_entities[entity_id] = true
		end
	end

	-- reset actions for scout if it no longer has a line of sight
	-- don't know what can possibly cause this but...
	-- for _, entity in world:active_entities() do
	-- 	if entity.type == "scout" then
	-- 		local extracted = util.table_extract(entity.queued_decisions, function(action)
	-- 			if action.type == "scout_attack" then
	-- 				if
	-- 					not world_mod.line_of_sight(world, entity.primary_coordinate, action.coordinate, entity.owner)
	-- 				then
	-- 					return true
	-- 				end
	-- 			end
	-- 			return false
	-- 		end)
	-- 		if #extracted > 0 then
	-- 			warn("Scout lost line of sight", data)
	-- 			dirty_entities[entity.id] = true
	-- 		end
	-- 	end
	-- end

	for entity_id in dirty_entities do
		world:add_update {
			type = "entity_update",
			entity = world.entities[entity_id],
		}
	end

	for _, quest in world.quests do
		questing.quest_update(quest, world)
	end

	world_mod.destroy_orphan_entities(world)

	local updates = updates_mod.flush_updates(world)

	world_mod.purge_destroyed_entities(world)
	return {
		error_type = 0,
		updates = updates,
	}
end

return {
	on_client_interaction = on_client_interaction,
	handle_interaction = handle_interaction,
}
