local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"

local types = require(ReplicatedStorage.Shared.types)
local util = require(ReplicatedStorage.Shared.util)

local server_types = require(ServerScriptService.Server.types)
local server_entity_mod = require(ServerScriptService.Server.entity)
local updates_mod = require(ServerScriptService.Server.updates)
local computed_mod = require(ServerScriptService.Server.computed)
local quest_methods = require(ServerScriptService.Server.questing.quest)
local effects_mod = require(ServerScriptService.Server.effect)
local visibility_mod = require(ServerScriptService.Server.visibility)

local do_entity_decay = require(script.entity_decay).do_entity_decay
local new_action_state = require(script.new_action_state).new_action_state
local create_systems = require(script.create_systems).create_systems
local process_queue = require(script.process_queue).process_queue

type World = types.World
type EntityId = types.EntityId
type ActionState = server_types.ActionState
type EntityAction = types.EntityAction
type TeamId = types.TeamId
type System = server_types.System

function portals_tick(world: World)
	for _, cell in world.cells do
		if cell.type == "portal" then
			local max_steps = cell.portal.open_time + cell.portal.close_time
			cell.portal.steps = (cell.portal.steps + 1) % max_steps
			if cell.portal.steps < cell.portal.open_time then
				cell.portal.open = true
			else
				cell.portal.open = false
			end
		end
	end
end

function queue_entity_decisions(world: World, queue: { EntityAction })
	for _, entity in world:active_entities() do
		for _, decision in entity.queued_decisions do
			table.insert(queue, decision)
			updates_mod.add_update(world, {
				type = "entity_update",
				entity = entity,
			})
		end
		entity.queued_decisions = {}
	end
end

function queue_blueprints_and_scaffolds(world: World, queue: { EntityAction })
	for _, entity in world:active_entities() do
		-- queue all scaffolds for advancement
		if entity.status == "scaffold" then
			table.insert(queue, {
				type = "try_promote_scaffold",
				entity_id = entity.id,
			})
		elseif entity.status == "blueprint" and not entity.autogenerated then
			table.insert(queue, {
				type = "try_promote_blueprint",
				entity_id = entity.id,
			})
		end
	end
end

function remove_occuluded_blueprints(world: World)
	-- remove blueprints that are too close to enemies
	for _, entity in world:active_entities() do
		if entity.status == "blueprint" then
			local cell = world:get_cell(entity.primary_coordinate)
			if
				util.table_any(util.table_keys(cell.server_data.presence), function(team)
					if team ~= entity.owner then
						return true
					end
					return false
				end)
			then
				server_entity_mod.remove_entity(world, entity)
			end
		end
	end
end

function status_effects_tick(world: World)
	local effects = effects_mod.effects
	for entity_id, entity in world:active_entities() do
		if next(entity.effects) == nil then
			continue
		end
		for _, effect in entity.effects do
			if effects[effect.type] then
				if effects[effect.type].tick then
					effects[effect.type].tick(world, entity, effect)
				end
			end
			if effect.duration ~= nil then
				effect.duration -= 1
				if effect.duration <= 0 then
					effect.is_destroyed = true
				end
			end
		end
		effects_mod.purge_destroyed_effects(entity)
		updates_mod.add_update(world, {
			type = "entity_update",
			entity = entity,
		})
	end
end

--- Requires influences to be computed
function entities_tick(world: World, action_state: ActionState)
	for _, entity in world:active_entities() do
		local server_behavior = server_entity_mod.registry[entity.type]
		server_behavior.tick(entity, world, action_state)
	end
end

function delete_deconstructed_entities(world: World, queue: { EntityAction })
	for _, action in
		util.table_extract(queue, function(a: EntityAction)
			return a.type == "deconstruct"
		end)
	do
		local entity = world.entities[action.entity_id]
		-- decaying entities can't be deconstructed
		if entity.is_decaying then
			table.insert(queue, action)
			continue
		end

		server_entity_mod.remove_entity(world, entity)
	end
end

function run_action_phase(world: World, extra_actions: { EntityAction }?)
	local t0 = tick()
	local action_state = new_action_state()

	if extra_actions then
		for _, action in extra_actions do
			if action.type == nil then
				error "not an action"
			end
			table.insert(world.action_queue, action)
		end
	end

	queue_entity_decisions(world, world.action_queue)
	delete_deconstructed_entities(world, world.action_queue)
	portals_tick(world)

	computed_mod.compute_influences(world)
	entities_tick(world, action_state)

	queue_blueprints_and_scaffolds(world, world.action_queue)

	create_systems(world, action_state)
	process_queue(world, action_state)

	status_effects_tick(world)

	-- destroy entities marked for destruction
	for entity_id in action_state.will_be_destroyed_entities do
		server_entity_mod.remove_entity(world, world.entities[entity_id])
	end

	create_systems(world, action_state)
	do_entity_decay(world, action_state)

	computed_mod.compute_presence(world)
	remove_occuluded_blueprints(world)

	for team_id, changed_to_visible in visibility_mod.compute_visibility(world) do
		for encoded_coord in changed_to_visible do
			local cell = world.cells[encoded_coord]
			for entity_id in cell.entities do
				updates_mod.add_update(world, {
					type = "entity_update",
					entity = world.entities[entity_id],
					targets = {
						team_id,
					},
				})
			end
		end
	end

	updates_mod.add_update(world, {
		type = "cells",
		cells = world.cells,
	})

	world.turn += 1
	updates_mod.add_update(world, {
		type = "turn",
		turn = world.turn,
		highest_turn = world.highest_turn,
	})

	for _, quest in world.quests do
		quest_methods.quest_update(quest, world)
	end

	local updates = updates_mod.flush_updates(world)
	world:purge_dead_entities()

	return {
		elapsed = tick() - t0,
		updates = updates,
	}
end

return {
	run_action_phase = run_action_phase,
}
