local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"

local types = require(ReplicatedStorage.Shared.types)
local util = require(ReplicatedStorage.Shared.util)
local hex_grid_mod = require(ReplicatedStorage.Shared.hex_grid)
local items_mod = require(ReplicatedStorage.Shared.items)

local server_types = require(ServerScriptService.Server.types)
local server_entity_mod = require(ServerScriptService.Server.entity)
local server_util = require(ServerScriptService.Server.util)
local damage_mod = require(ServerScriptService.Server.damage)
local serialize_mod = require(ServerScriptService.Server.serialize)
local updates_mod = require(ServerScriptService.Server.updates)
local systems_mod = require(ServerScriptService.Server.systems)
local researches_mod = require(ReplicatedStorage.Shared.researches)
local computed_mod = require(ServerScriptService.Server.computed)

type HexGrid = types.HexGrid
type Entity = types.Entity
type EntityId = types.EntityId
type GridUpdate = types.GridUpdate
type CubicCoordinate = types.CubicCoordinate
type EncodedCoordinate = types.EncodedCoordinate
type ActionState = server_types.ActionState
type Inventory = types.Inventory
type EntityAction = server_types.EntityAction
type Item = types.Item
type HexCell = types.HexCell
type TeamId = types.TeamId
type System = server_types.System

function mark_dirty_for_everyone(action_state: ActionState, entity_id: EntityId)
	action_state.dirty_entities[entity_id] = action_state.dirty_entities[entity_id] or {}
	action_state.dirty_entities[entity_id].everyone = true
end

function run_action_phase(grid: HexGrid)
	local t0 = tick()

	local action_state = {
		queue = {},
		dirty_entities = {},
		dead_entities = {},
		decayable_entities = {},
	} :: ActionState

	computed_mod.compute_influences(grid)

	for _, entity in grid.entities do
		if entity.status ~= "blueprint" and entity.owner ~= grid.neutral_team and entity.decayable then
			action_state.decayable_entities[entity.id] = true
		end

		for _, decision in entity.queued_decisions do
			table.insert(action_state.queue, decision)
			mark_dirty_for_everyone(action_state, entity.id)
		end
		entity.queued_decisions = {}
		local server_behavior = server_entity_mod.registry[entity.type]
		server_behavior.tick(entity, grid, action_state)

		-- queue all scaffolds for advancement
		if entity.status == "scaffold" then
			table.insert(action_state.queue, {
				type = "try_promote_scaffold",
				entity_id = entity.id,
			})
		end
	end

	for _, action in
		util.table_extract(action_state.queue, function(a: EntityAction)
			return a.type == "deconstruct"
		end)
	do
		local entity = grid.entities[action.entity_id]
		if entity.is_decaying then
			table.insert(action_state.queue, action)
		else
			updates_mod.push_buffer(grid)
			server_entity_mod.remove_entity(grid, entity, action_state)
			server_entity_mod.trigger_neighbors(grid, entity.primary_coordinate, action_state)
			updates_mod.pop_buffer(grid)
		end
	end

	for _, cell in grid.cells do
		if cell.type == "portal" then
			local max_steps = cell.portal.open_time + cell.portal.close_time
			cell.portal.steps = (cell.portal.steps + 1) % max_steps
			if cell.portal.steps < cell.portal.open_time then
				cell.portal.open = true
			else
				cell.portal.open = false
			end
		end
	end

	-- if scaffold is queued for decon, try_promote_scaffold gets added to the action queue, but the entity is removed afterwards, not good

	computed_mod.compute_systems(grid)
	computed_mod.compute_influences(grid)
	for _, entities in grid.systems do
		local system = {
			entities = entities,
			overflow_items = {},
			power = 0,
			team = grid.entities[next(entities) :: any].owner,
		} :: System

		-- mark blueprints neighboring the system for promotion
		for neighbor in
			server_util.get_neighbors_set(
				grid,
				util.table_flat(util.table_map(util.table_keys(system.entities), function(id)
					return grid.entities[id].coordinates
				end))
			)
		do
			if grid.cells[neighbor] then
				for _, entity_id in grid.cells[neighbor].entities do
					local entity = grid.entities[entity_id]
					if entity.owner == system.team and entity.status == "blueprint" and not entity.autogenerated then
						table.insert(action_state.queue, {
							type = "try_promote_blueprint",
							entity_id = entity_id,
						})
					end
				end
			end
		end

		-- promote blueprints on portals
		for _, entity_id in util.table_keys(system.entities) do
			local entity = grid.entities[entity_id]
			local cell = grid:get_cell(entity.primary_coordinate)
			if cell.type == "portal" and cell.portal.open then
				for _, coord in cell.portal.group do
					if hex_grid_mod.coords_eq(coord, entity.primary_coordinate) then
						continue
					end
					local connected_cell = grid:get_cell(coord)
					for _, connected_entity_id in connected_cell.entities do
						local connected_entity = grid.entities[connected_entity_id]
						if
							connected_entity.owner == system.team
							and connected_entity.status == "blueprint"
							and not connected_entity.autogenerated
						then
							table.insert(action_state.queue, {
								type = "try_promote_blueprint",
								entity_id = connected_entity_id,
							})
						end
					end
				end
			end
		end

		local old_queue
		local iterations = 0
		local MAX_ALLOWED_ITERATIONS = 100
		local function should_terminate(): boolean
			if iterations > MAX_ALLOWED_ITERATIONS then
				warn "MAX_ALLOWED_ITERATIONS reached"
				return true
			end
			iterations += 1
			if #old_queue ~= #action_state.queue then
				return false
			end
			for i, action in old_queue do
				if action ~= action_state.queue[i] then
					return false
				end
			end
			return true
		end

		-- essentially, attempt to fulfill as many actions as possible in a certain order
		-- only stopping once none can be fulfilled anymore

		-- This might enter an infinite loop if in 2n iteration it moves action A to the end, then in iteration 2n+1 it moves action B to the end

		repeat
			old_queue = {}
			for _, action in action_state.queue do
				table.insert(old_queue, action)
			end

			for _, exchange_action: any in
				util.table_extract(action_state.queue, function(action)
					return (action.type == "exchange" or action.type == "exchange_promise")
						and table.find(util.table_keys(system.entities), action.entity_id) ~= nil
				end)
			do
				local input_items = exchange_action.input_items
				local output_items = exchange_action.output_items
				local input_power = exchange_action.input_power or 0
				local output_power = exchange_action.output_power or 0
				if
					(input_items and not systems_mod.system_has_items(grid, action_state, system, input_items))
					or (system.power < input_power)
				then
					table.insert(action_state.queue, exchange_action)
					continue
				end
				if input_items then
					for item_type, amount in input_items do
						systems_mod.system_consume_item_type(grid, action_state, system, item_type, amount)
					end
				end
				system.power -= input_power
				if exchange_action.on_success then
					exchange_action.on_success(grid, action_state, system)
				end
				if output_items then
					local out = {}
					for _, item_type in output_items do
						table.insert(out, item_type)
					end

					systems_mod.system_add_items(grid, action_state, system, out)
				end
				system.power += output_power
				table.insert(grid.updates_buffer[#grid.updates_buffer], exchange_action)
			end

			for _, ability in
				util.table_extract(action_state.queue, function(value)
					return (value.type == "ability")
						and table.find(util.table_keys(system.entities), value.entity_id) ~= nil
				end)
			do
				local shared_behavior = grid.entity_configurations[grid.entities[ability.entity_id].type]
				local cost = shared_behavior.abilities[ability.ability_type].cost

				mark_dirty_for_everyone(action_state, ability.entity_id)
				if not systems_mod.system_has_items(grid, action_state, system, cost :: any) then
					continue
				end

				for item_type, amount in cost do
					systems_mod.system_consume_item_type(grid, action_state, system, item_type, amount)
				end
				table.insert(grid.updates_buffer[#grid.updates_buffer], {
					type = "exchange",
					input_items = cost,
					entity_id = ability.entity_id,
					target = grid:get_allies(grid.entities[ability.entity_id].owner),
				})

				local entity = grid.entities[ability.entity_id]

				local cell = grid:get_cell(ability.coordinate)
				if not cell then
					return
				end
				table.insert(grid.updates_buffer[#grid.updates_buffer], ability)
				damage_mod.apply_damage_on_cells(grid, { cell.coordinate }, {
					type = "flat",
					amount = if ability.ability_type == "scout_attack" then 1 else 3,
					from = entity.id,
					lethal = true,
					friendly_fire = false,
				}, action_state)
			end

			local try_promote_actions: { EntityAction } = util.table_extract(action_state.queue, function(action)
				return (action.type == "try_promote_blueprint" or action.type == "try_promote_scaffold")
					and grid.entities[action.entity_id] ~= nil
			end)
			table.sort(try_promote_actions, function(a, b)
				local entity_a = grid.entities[a.entity_id]
				local entity_b = grid.entities[b.entity_id]
				return entity_a.server_data.requested_at < entity_b.server_data.requested_at
			end)
			for _, action in try_promote_actions do
				local entity = grid.entities[action.entity_id]
				local server_behavior = server_entity_mod.registry[entity.type]
				local shared_config = grid.entity_configurations[entity.type]

				if action.type == "try_promote_blueprint" then
					local cell = grid:get_cell(entity.primary_coordinate)
					assert(cell, "cell not found")
					local cell_researches = researches_mod.get_cell_researches(grid, cell, entity.owner)
					if
						shared_config.required_research
						and not util.table_every(shared_config.required_research, function(research_id)
							return cell_researches[research_id]
						end)
					then
						-- this blueprint is not researched and therefore cannot be promoted
						table.insert(action_state.queue, action)
						continue
					end

					local consumed = {}
					-- attempt to satisfy entity.cost_fulfilled as much as possible
					for request_item_type, request_amount in entity.cost do
						if not entity.cost_fulfilled[request_item_type] then
							entity.cost_fulfilled[request_item_type] = 0
						end
						local difference = request_amount - entity.cost_fulfilled[request_item_type]
						local net = systems_mod.system_consume_item_type(
							grid,
							action_state,
							system,
							request_item_type,
							difference
						)
						entity.cost_fulfilled[request_item_type] += net
						if net > 0 then
							mark_dirty_for_everyone(action_state, entity.id)
							consumed[request_item_type] = net
						end
					end
					table.insert(grid.updates_buffer[#grid.updates_buffer], {
						type = "exchange",
						input_items = consumed,
						entity_id = entity.id,
						-- todo: include coalitions
						target = { entity.owner },
					})
					if util.deep_equal(entity.cost, entity.cost_fulfilled) then
						entity.status = "scaffold"
						mark_dirty_for_everyone(action_state, entity.id)
						if server_behavior.autogenerate_wires then
							local wires = grid:query_entity({
								primary_coordinate = entity.primary_coordinate,
								type = "wires",
								owner = entity.owner,
							})[1]
							wires.status = "scaffold"
							mark_dirty_for_everyone(action_state, wires.id)
						end
					else
						-- put this action back in the queue
						table.insert(action_state.queue, action)
					end
					-- if entity.cost_fulfilled deep_equal entity.cost then entity can promote to
				elseif action.type == "try_promote_scaffold" and entity.build_time > 0 then
					entity.build_time -= 1
					mark_dirty_for_everyone(action_state, entity.id)
				end
				if entity.status == "scaffold" and entity.build_time == 0 then
					entity.status = "complete"
					server_behavior.on_completed(entity, grid, action_state)
					mark_dirty_for_everyone(action_state, entity.id)
					local wires = grid:query_entity({
						primary_coordinate = entity.primary_coordinate,
						type = "wires",
						owner = entity.owner,
					})[1]
					if wires then
						wires.status = "complete"
						mark_dirty_for_everyone(action_state, wires.id)
					end
				end
			end

			local advance_research_actions: { EntityAction } = util.table_extract(action_state.queue, function(action)
				return action.type == "advance_research"
					and table.find(util.table_keys(system.entities), action.entity_id) ~= nil
			end)
			for _, action in advance_research_actions do
				local entity = grid.entities[action.entity_id]
				if not entity or entity.is_destroyed then
					error "advance_research error"
				end

				for _, research_id in entity.researches.queue do
					local research_state = entity.researches.states[research_id]
					if not research_state.cost_is_paid then
						if not systems_mod.system_has_items(grid, action_state, system, research_state.cost) then
							break
						end

						for item_type, amount in research_state.cost do
							systems_mod.system_consume_item_type(grid, action_state, system, item_type, amount)
						end
						table.insert(grid.updates_buffer[#grid.updates_buffer], {
							type = "exchange",
							input_items = research_state.cost,
							entity_id = entity.id,
							target = grid:get_allies(entity.owner),
						})
						research_state.cost_is_paid = true
						mark_dirty_for_everyone(action_state, entity.id)
					else
						research_state.progress += 1
						mark_dirty_for_everyone(action_state, entity.id)
					end

					if research_state.progress == research_state.time then
						research_state.status = "complete"
						-- TODO: handle research completion -- ?
						mark_dirty_for_everyone(action_state, entity.id)
					else
						break
					end
				end

				local _finished = util.table_extract(entity.researches.queue, function(research_id)
					return entity.researches.states[research_id].status == "complete"
				end)
			end

			-- add overflow items to inventory
			for _, open_inventory_entity in
				util.table_filter_map(util.table_keys(system.entities), function(entity_id)
					local inventory = grid.entities[entity_id].inventory
					if inventory and inventory.capacity > #inventory.items then
						return grid.entities[entity_id]
					end
					return nil
				end)
			do
				if #system.overflow_items == 0 then
					break
				end
				items_mod.inventory_deposit(open_inventory_entity.inventory, system.overflow_items)
			end
		until should_terminate()

		-- then discard all the actions that shouldn't carry over
		local _discarded = util.table_extract(action_state.queue, function(action)
			return table.find({
				"try_promote_blueprint",
				"try_promote_scaffold",
			}, action.type) ~= nil
		end)
	end

	updates_mod.push_buffer(grid)
	for entity_id in action_state.dead_entities do
		server_entity_mod.remove_entity(grid, grid.entities[entity_id], action_state)
	end

	computed_mod.compute_systems(grid)

	for _, entities in grid.systems do
		local has_heart = false
		for entity_id in entities do
			local entity = grid.entities[entity_id]
			if entity.type == "heart" or entity.type == "infinite_source" then
				has_heart = true
			end
		end

		for neighbor in
			server_util.get_neighbors_set(
				grid,
				util.table_flat(util.table_map(util.table_keys(entities), function(id)
					return grid.entities[id].coordinates
				end))
			)
		do
			if grid.cells[neighbor] then
				for _, entity_id in grid.cells[neighbor].entities do
					local entity = grid.entities[entity_id]
					if entity.status == "scaffold" then
						action_state.decayable_entities[entity_id] = false
					end
				end
			end
		end

		for entity_id in entities do
			if has_heart then
				action_state.decayable_entities[entity_id] = false
			end
		end
	end

	updates_mod.push_buffer(grid)
	for entity_id, should_decay in action_state.decayable_entities do
		local entity = grid.entities[entity_id]
		if entity == nil then
			warn("entity not found", entity_id)
			continue
		end

		if should_decay then
			entity.is_decaying = true
			entity.decay += 1
			mark_dirty_for_everyone(action_state, entity_id)
			if entity.decay >= 3 then
				if entity.type == "wires" then
					server_entity_mod.remove_entity(grid, entity, action_state)
				else
					entity.owner = grid.neutral_team
					entity.decay = 0
				end
			end
		else
			if entity.is_decaying then
				entity.is_decaying = false
				entity.decay = 0
				mark_dirty_for_everyone(action_state, entity_id)
			end
		end
	end
	updates_mod.pop_buffer(grid)

	computed_mod.compute_presence(grid)
	for _, entity in grid.entities do
		if entity.status == "blueprint" then
			local cell = grid:get_cell(entity.primary_coordinate)
			if
				util.table_any(util.table_keys(cell.server_data.presence), function(team)
					if team ~= entity.owner then
						return true
					end
					return false
				end)
			then
				server_entity_mod.remove_entity(grid, entity, action_state)
			end
		end
	end
	updates_mod.pop_buffer(grid)

	computed_mod.compute_visibility(grid, action_state)

	table.insert(grid.updates_buffer[#grid.updates_buffer], {
		type = "cells",
		cells = grid.cells,
	})

	for entity_id, values in action_state.dirty_entities do
		local entity = grid.entities[entity_id]
		if entity == nil then
			-- dirty entity was probably deleted nothing to worry about
			continue
		end
		if values.everyone then
			table.insert(grid.updates_buffer[#grid.updates_buffer], {
				type = "entity_update",
				entity = entity,
			})
		else
			local targets: { TeamId } = {}
			for _, team_id in util.table_keys(values) do
				table.insert(targets, team_id)
			end
			table.insert(grid.updates_buffer[#grid.updates_buffer], {
				type = "entity_update",
				entity = entity,
				targets = targets,
			})
		end
	end

	grid.turn += 1
	table.insert(grid.updates_buffer[#grid.updates_buffer], {
		type = "turn",
		turn = grid.turn,
		highest_turn = grid.highest_turn,
	})
	local updates_copy = table.clone(grid.updates_buffer[#grid.updates_buffer])

	updates_mod.flush_updates(grid)
	grid:purge_dead_entities()

	return {
		elapsed = tick() - t0,
		updates = updates_copy,
	}
end

return {
	run_action_phase = run_action_phase,
	serialize_grid_for_team = serialize_mod.serialize_grid_for_team,
}
