local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"

local types = require(ReplicatedStorage.Shared.types)
local util = require(ReplicatedStorage.Shared.util)
local world_mod = require(ReplicatedStorage.Shared.world)
local team_mod = require(ReplicatedStorage.Shared.team)
local coords = require(ReplicatedStorage.Shared.coords)

local presence_mod = require(ServerScriptService.Server.presence)
local server_types = require(ServerScriptService.Server.types)
local server_entity_mod = require(ServerScriptService.Server.entity)
local updates_mod = require(ServerScriptService.Server.updates)
local influences_mod = require(ServerScriptService.Server.influences)
local questing = require(ServerScriptService.Server.questing)
local effect_mod = require(ServerScriptService.Server.effect)
local visibility_mod = require(ServerScriptService.Server.visibility)
local entity_mod = require(ServerScriptService.Server.entity)

local do_entity_decay = require(script.entity_decay).do_entity_decay
local new_action_state = require(script.new_action_state).new_action_state
local create_systems = require(script.create_systems).create_systems
local process_queue = require(script.process_queue).process_queue

type World = types.World
type EntityId = types.EntityId
type ActionState = server_types.ActionState
type EntityAction = types.EntityAction
type TeamId = types.TeamId
type System = types.System
type Effect = types.Effect

function portals_tick(world: World)
	for _, cell in world.cells do
		if cell.type == "portal" then
			local max_steps = cell.portal.open_time + cell.portal.close_time
			cell.portal.steps = (cell.portal.steps + 1) % max_steps
			if cell.portal.steps < cell.portal.open_time then
				cell.portal.open = true
			else
				cell.portal.open = false
			end
		end
	end
end

-- add all entities' queued_decisions into the global action queue
function queue_entity_decisions(world: World, queue: { EntityAction })
	for _, entity in world:active_entities() do
		for _, decision in entity.queued_decisions do
			decision.entity_id = entity.id

			table.insert(queue, decision)
			world:add_update {
				type = "entity_update",
				entity = entity,
			}
		end
		entity.queued_decisions = {}
	end
end

function queue_blueprints_and_scaffolds(world: World, queue: { EntityAction })
	for _, entity in world:active_entities() do
		-- queue all scaffolds for advancement
		if entity.status == "scaffold" then
			table.insert(queue, {
				type = "try_promote_scaffold",
				entity_id = entity.id,
			})
		elseif entity.status == "blueprint" and not entity.autogenerated then
			table.insert(queue, {
				type = "try_promote_blueprint",
				entity_id = entity.id,
			})
		end
	end
end

function remove_occluded_blueprints(world: World)
	-- remove blueprints that are too close to enemies
	-- presence is not allowed here cause we only want to remove
	-- blueprints that has a presence the team can observe
	for _, entity in world:active_entities() do
		if
			entity.status == "blueprint"
			and not presence_mod.team_may_naively_place_blueprint(world, entity.owner, entity.primary_coordinate)
		then
			-- then destroy the blueprint
			world:add_update {
				type = "entity_event",
				event_type = "destroy",
				entity_id = entity.id,
				death_type = "other",
			}
			entity_mod.remove_entity(world, entity)
		end
	end
end

function status_effects_tick(world: World, action_state: ActionState)
	local entity_and_effects: { [EntityId]: { Effect } } = {}

	-- clone table so only effects that existed at the start of the tick are ticked
	for entity_id, entity in world:active_entities() do
		if next(entity.effects) == nil then
			continue
		end
		entity_and_effects[entity_id] = table.clone(entity.effects)
	end

	for entity_id, effects in entity_and_effects do
		local entity = world.entities[entity_id]
		for _, effect in effects do
			local behavior = effect_mod.registry[effect.type]
			if behavior then
				if behavior.tick then
					behavior.tick(world, action_state, entity, effect)
				end
			end
			if effect.duration ~= nil then
				effect.duration -= 1
				if effect.duration <= 0 then
					behavior.remove(world, entity, effect)
					effect.is_destroyed = true
				end
			end
		end

		effect_mod.purge_destroyed_effects(entity)
		world:add_update {
			type = "entity_update",
			entity = entity,
		}
	end
end

--- Requires influences to be computed
function entities_tick(world: World, action_state: ActionState)
	for _, entity in world:active_entities() do
		local server_behavior = server_entity_mod.registry[entity.type]
		server_behavior.tick(entity, world, action_state)
	end
end

function delete_deconstructed_entities(world: World, queue: { EntityAction })
	for _, action in
		util.table_extract(queue, function(a: EntityAction)
			return a.type == "deconstruct"
		end)
	do
		local entity = world.entities[action.entity_id]
		-- decaying entities can't be deconstructed
		if entity.is_decaying then
			table.insert(queue, action)
			continue
		end
		local event = {
			type = "entity_event",
			event_type = "destroy",
			entity_id = entity.id,
			death_type = "deconstruct",
		}
		table.insert(queue, event)
		world:add_update(event)
		entity_mod.remove_entity(world, entity)
	end
end

function run_action_phase(world: World, extra_actions: { EntityAction }?)
	local t0 = tick()
	local action_state = new_action_state()

	if #world.action_queue > 0 then
		warn("there are leftover actions in the action queue", world.action_queue)
	end

	if extra_actions then
		for _, action in extra_actions do
			if action.type == nil then
				error "not an action"
			end
			table.insert(world.action_queue, action)
		end
	end

	queue_entity_decisions(world, world.action_queue)
	delete_deconstructed_entities(world, world.action_queue)
	portals_tick(world)

	visibility_mod.compute_visibility(world)
	influences_mod.compute_influences(world)
	presence_mod.compute_presence(world)
	create_systems(world, action_state)

	entities_tick(world, action_state)
	status_effects_tick(world, action_state)

	queue_blueprints_and_scaffolds(world, world.action_queue)

	for _, entity in world:active_entities() do
		if entity.status == "complete" and entity.owner ~= world.neutral_team and entity.researches ~= nil then
			table.insert(world.action_queue, {
				type = "advance_research",
				entity_id = entity.id,
			})
		end
	end

	local dropped = process_queue(world, action_state)

	for _, entity in world:active_entities() do
		if entity.type == "vertex" or entity.type == "extractor" then
			continue
		end
		local on_vit = false
		local on_rad = false
		for _, coord in entity.coordinates do
			local cell = world:get_cell(coord)
			if cell.type == "vit_deposit" then
				on_vit = true
			elseif cell.type == "rad_deposit" then
				on_rad = true
			end
		end
		if on_vit then
			effect_mod.add_exclusive_effect(world, entity, {
				type = "regeneration",
				duration = 2,
			})
		end
	end

	for _, entity in world:active_entities() do
		if entity.server_data.will_die then
			entity_mod.remove_entity(world, entity)
		end
	end

	create_systems(world, action_state)
	do_entity_decay(world, action_state)

	influences_mod.compute_influences(world) --recompute influences if entities DIE
	presence_mod.compute_presence(world)
	visibility_mod.compute_visibility(world)
	remove_occluded_blueprints(world)

	-- add entity update for all cells that are now visible to a team
	-- only do this for changed_to_true that was set this turn that are still visible
	for _, cell in world.cells do
		for team_id, visibility in cell.server_data.visibility do
			if not visibility.changed_to_true then
				continue
			end
			visibility.changed_to_true = false
			if not visibility_mod.cell_visibility(visibility) then
				continue
			end
			for entity_id in cell.entities do
				world:add_update {
					type = "entity_update",
					entity = world.entities[entity_id],
					targets = {
						team_id,
					},
				}
			end
		end
	end

	world:add_update {
		type = "cells",
		cells = world.cells,
	}

	world:add_update {
		type = "systems",
		systems = world.systems,
	}

	world.turn += 1
	world:add_update {
		type = "turn",
		turn = world.turn,
		highest_turn = world.highest_turn,
	}
	world:add_update {
		type = "turn_completed",
	}

	for _, quest in world.quests do
		questing.quest_update(quest, world)
	end

	local updates = updates_mod.flush_updates(world)
	world_mod.purge_destroyed_entities(world)

	return {
		elapsed = tick() - t0,
		updates = updates,
		dropped = dropped,
	}
end

return {
	run_action_phase = run_action_phase,
}
