local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"
local types = require(ReplicatedStorage.Shared.types)
local server_types = require(ServerScriptService.Server.types)
local server_util = require(ServerScriptService.Server.util)
local validate_condition = require(ReplicatedStorage.Shared.construction_condition).validate_condition

local util = require(ReplicatedStorage.Shared.util)
local systems_mod = require(ServerScriptService.Server.systems)
local server_entity_mod = require(ServerScriptService.Server.entity)
local researches_mod = require(ReplicatedStorage.Shared.researches)

type World = types.World
type EntityAction = types.EntityAction

function handle_try_promote_actions(world: World)
	local try_promote_actions: { EntityAction } = util.table_extract(world.action_queue, function(action)
		if action.type == "try_promote_blueprint" or action.type == "try_promote_scaffold" then
			return true
		end
		return false
	end)

	table.sort(try_promote_actions, function(a, b)
		local entity_a = world.entities[a.entity_id]
		local entity_b = world.entities[b.entity_id]
		return entity_a.server_data.requested_at < entity_b.server_data.requested_at
	end)
	for _, action in try_promote_actions do
		local entity = world.entities[action.entity_id]
		local server_behavior = server_entity_mod.registry[entity.type]
		local config = world.entity_configurations[entity.type]

		if action.type == "try_promote_blueprint" then
			if world.global_configuration.construction_condition_enabled then
				local ok =
					validate_condition(world, entity.coordinates, entity.owner, config.construction_condition, false)
				if not ok then
					continue
				end
			end

			local valid_systems = {}

			-- can promote if it is neighboring a system
			for encoded_neighbor, neighbor in server_util.get_neighbors_set(world, entity.coordinates) do
				local system = world.systems[world.cell_system_map[encoded_neighbor]]
				if system ~= nil and system.team == entity.owner then
					table.insert(valid_systems, system)
				end
			end

			local cell = world:get_cell(entity.primary_coordinate)

			if #valid_systems == 0 then
				continue
			end
			for _, system in valid_systems do
				-- is this blueprint researched?
				local cell_researches = researches_mod.get_cells_researches(world, { cell }, entity.owner)
				if
					config.required_research
					and not util.table_every(config.required_research, function(research_id)
						return cell_researches[research_id]
					end)
				then
					continue
				end

				-- attempt to satisfy entity.cost_fulfilled as much as possible
				local consumed = {}
				for request_item_type, request_amount in entity.cost do
					if not entity.cost_fulfilled[request_item_type] then
						entity.cost_fulfilled[request_item_type] = 0
					end
					local difference = request_amount - entity.cost_fulfilled[request_item_type]
					local net = systems_mod.system_consume_item_type(world, system, request_item_type, difference)
					entity.cost_fulfilled[request_item_type] += net
					if net > 0 then
						world:add_update {
							type = "entity_update",
							entity = entity,
						}
						consumed[request_item_type] = net
					end
				end

				local event = {
					type = "entity_event",
					event_type = "consumed_items",
					entity_id = entity.id,
					items = consumed,
				}
				table.insert(world.action_queue, event)
				world:add_update(event)

				-- if entity.cost_fulfilled deep_equal entity.cost then entity can promote to
				if util.deep_equal(entity.cost, entity.cost_fulfilled) then
					entity.status = "scaffold"
					if system.heart == "anima" then
						if entity.max_health > 0 then
							entity.max_health -= 1
							entity.health = entity.max_health
						end
					end

					world:add_update {
						type = "entity_update",
						entity = entity,
					}
					if server_behavior.autogenerates_vertex then
						local vertex = world:query_entity({
							coordinate = entity.primary_coordinate,
							type = "vertex",
							owner = entity.owner,
						})[1]
						if vertex then
							if vertex.autogenerated and vertex.status == "blueprint" then
								vertex.status = "complete"
								vertex.autogenerated = nil
							end
							world:add_update {
								type = "entity_update",
								entity = vertex,
							}
						else
							warn "This scaffold has no corresponding vertex"
						end
					end

					break
				end
			end
		elseif action.type == "try_promote_scaffold" and entity.build_time > 0 then
			entity.build_time -= 1
			world:add_update {
				type = "entity_update",
				entity = entity,
			}
		end

		-- if this blueprint is still not promoted, add it back to the queue
		if entity.status == "blueprint" then
			table.insert(world.action_queue, action)
		-- if this blueprint, now a scaffold has a build time of zero, complete it immediately
		elseif entity.status == "scaffold" and entity.build_time == 0 then
			entity.status = "complete"
			server_behavior.on_completed(entity, world)
			world:add_update {
				type = "entity_update",
				entity = entity,
			}
			local vertex = world:query_entity({
				coordinate = entity.primary_coordinate,
				type = "vertex",
				owner = entity.owner,
			})[1]
			if vertex and vertex.status ~= "complete" then
				vertex.status = "complete"
				vertex.autogenerated = nil
				world:add_update {
					type = "entity_update",
					entity = vertex,
				}
			end
		end
	end
end

return {
	handle_try_promote_actions = handle_try_promote_actions,
}
