local ReplicatedStorage = game:GetService "ReplicatedStorage"
local ServerScriptService = game:GetService "ServerScriptService"
local types = require(ReplicatedStorage.Shared.types)
local server_types = require(ServerScriptService.Server.types)
local publish_event = require(ServerScriptService.Server.event).publish_event
local server_util = require(ServerScriptService.Server.util)

local util = require(ReplicatedStorage.Shared.util)
local systems_mod = require(ServerScriptService.Server.systems)
local hex_grid_mod = require(ReplicatedStorage.Shared.hex_grid)
local server_entity_mod = require(ServerScriptService.Server.entity)
local researches_mod = require(ReplicatedStorage.Shared.researches)

type HexGrid = types.HexGrid
type System = server_types.System
type ActionState = server_types.ActionState
type EntityAction = server_types.EntityAction

function handle_try_promote_actions(grid: HexGrid, action_state: ActionState, system: System)
	local try_promote_actions: { EntityAction } = util.table_extract(action_state.queue, function(action)
		return (action.type == "try_promote_blueprint" or action.type == "try_promote_scaffold")
			and grid.entities[action.entity_id] ~= nil
	end)
	table.sort(try_promote_actions, function(a, b)
		local entity_a = grid.entities[a.entity_id]
		local entity_b = grid.entities[b.entity_id]
		return entity_a.server_data.requested_at < entity_b.server_data.requested_at
	end)
	for _, action in try_promote_actions do
		local entity = grid.entities[action.entity_id]
		local server_behavior = server_entity_mod.registry[entity.type]
		local shared_config = grid.entity_configurations[entity.type]

		if action.type == "try_promote_blueprint" then
			local cell = grid:get_cell(entity.primary_coordinate)
			assert(cell, "cell not found")
			local cell_researches = researches_mod.get_cell_researches(grid, cell, entity.owner)
			if
				shared_config.required_research
				and not util.table_every(shared_config.required_research, function(research_id)
					return cell_researches[research_id]
				end)
			then
				-- this blueprint is not researched and therefore cannot be promoted
				table.insert(action_state.queue, action)
				continue
			end

			local consumed = {}
			-- attempt to satisfy entity.cost_fulfilled as much as possible
			for request_item_type, request_amount in entity.cost do
				if not entity.cost_fulfilled[request_item_type] then
					entity.cost_fulfilled[request_item_type] = 0
				end
				local difference = request_amount - entity.cost_fulfilled[request_item_type]
				local net =
					systems_mod.system_consume_item_type(grid, action_state, system, request_item_type, difference)
				entity.cost_fulfilled[request_item_type] += net
				if net > 0 then
					server_util.mark_dirty_for_everyone(action_state, entity.id)
					consumed[request_item_type] = net
				end
			end

			publish_event(grid, {
				type = "consumed_items",
				entity_id = entity.id,
				items = consumed,
			}, hex_grid_mod.neighbors_leq(entity.primary_coordinate, 1))

			if util.deep_equal(entity.cost, entity.cost_fulfilled) then
				entity.status = "scaffold"
				server_util.mark_dirty_for_everyone(action_state, entity.id)
				if server_behavior.autogenerate_wires then
					local wires = grid:query_entity({
						primary_coordinate = entity.primary_coordinate,
						type = "wires",
						owner = entity.owner,
					})[1]
					if wires.autogenerated then
						wires.status = "scaffold"
					end
					server_util.mark_dirty_for_everyone(action_state, wires.id)
				end
			else
				-- put this action back in the queue
				table.insert(action_state.queue, action)
			end
			-- if entity.cost_fulfilled deep_equal entity.cost then entity can promote to
		elseif action.type == "try_promote_scaffold" and entity.build_time > 0 then
			entity.build_time -= 1
			server_util.mark_dirty_for_everyone(action_state, entity.id)
		end
		if entity.status == "scaffold" and entity.build_time == 0 then
			entity.status = "complete"
			server_behavior.on_completed(entity, grid, action_state)
			server_util.mark_dirty_for_everyone(action_state, entity.id)
			local wires = grid:query_entity({
				primary_coordinate = entity.primary_coordinate,
				type = "wires",
				owner = entity.owner,
			})[1]
			if wires then
				wires.status = "complete"
				server_util.mark_dirty_for_everyone(action_state, wires.id)
			end
		end
	end
end

return {
	handle_try_promote_actions = handle_try_promote_actions,
}
