require(script.vertex)
require(script.stockpile)
require(script.scout)
require(script.vault)
require(script.misc)
require(script.turret)
require(script.torch)
require(script.fountain)
require(script.phony)
require(script.obelisk)
require(script.necromancer)
require(script.deposit)
require(script.calamity)

return {}
