require(script.vertex)
require(script.stockpile)
require(script.extractor)
require(script.scout)
require(script.factory)
require(script.generator)
require(script.laboratory)
require(script.turret)
require(script.infinite_source)
require(script.barrier)
require(script.obelisk)
require(script.proxy)
require(script.heart)
require(script.vault)
require(script.solution)
require(script.witness)
require(script.impression)
require(script.phony)
require(script.suggestion)
require(script.taunt)
require(script.torch)
require(script.fountain)

return {}
