local HttpService = game:GetService "HttpService"
local ServerScriptService = game:GetService "ServerScriptService"
local ReplicatedStorage = game:GetService "ReplicatedStorage"
local hex_grid_mod = require(ReplicatedStorage.Shared.hex_grid)
local action_phase_mod = require(ServerScriptService.Server.action_phase)
local entity_mod = require(ServerScriptService.Server.entity)
local damage_mod = require(ServerScriptService.Server.damage)
local archive = require(ServerScriptService.Server.archive)
local presets = require(ServerScriptService.Server.presets)
local cleanup = require(ServerScriptService.Server.cleanup).cleanup

local tests = {}
function tests.extractor_filling_stockpile()
	-- Build the map
	local magic = 7

	local grid = hex_grid_mod.new_grid_from_extents {
		{ min = -magic, max = magic },
		{ min = -magic, max = magic },
		{ min = -magic, max = magic },
	}
	local team1 = grid:new_team({}, { type = "color3", color = Color3.new(1, 0.392156, 0.392156) })
	local team2 = grid:new_team({}, { type = "color3", color = Color3.new(0.301960, 0.403921, 1) })

	local extractor = entity_mod.new_entity({
		type = "extractor",
		status = "complete",
		primary_coordinate = { 6, -6, 0 },
		owner = team1.id,
		decayable = false,
	}, grid)
	local generator = entity_mod.new_entity({
		type = "generator",
		status = "complete",
		primary_coordinate = { 5, -6, 1 },
		owner = team1.id,
		decayable = false,
	}, grid)
	local stockpile = entity_mod.new_entity({
		type = "stockpile",
		status = "complete",
		primary_coordinate = { 5, -5, 0 },
		owner = team1.id,
		decayable = false,
	}, grid)

	grid:get_cell({ 6, -6, 0 }).type = "bar_deposit"

	for i = 1, 2 do
		action_phase_mod.run_action_phase(grid)
	end

	assert(#stockpile.inventory.items == 1, "expected 1 item in stockpile, got " .. #stockpile.inventory.items)

	for i = 1, 2 do
		action_phase_mod.run_action_phase(grid)
	end

	assert(#stockpile.inventory.items == 2, "expected 2 items in stockpile, got " .. #stockpile.inventory.items)

	for i = 1, 10 do
		action_phase_mod.run_action_phase(grid)
	end

	assert(
		#stockpile.inventory.items == stockpile.inventory.capacity,
		"expected all items in stockpile, got " .. #stockpile.inventory.items
	)

	cleanup(grid)
end

function tests.chatgpt_didnt_grift_me() -- (it did)
	local grid = hex_grid_mod.new_grid_from_extents {
		{ min = -5, max = 5 },
		{ min = -5, max = 5 },
		{ min = -5, max = 5 },
	}
	local team1 = grid:new_team({}, { type = "color3", color = Color3.new(1, 0.392156, 0.392156) })
	team1.server_data.visibility = "full"

	local result = hex_grid_mod.line_of_sight(grid, { -2, 0, 2 }, { 2, 0, -2 })
	assert(result == true, "no blockage: expected true")
	local barrier_at_origin = entity_mod.new_entity({
		type = "barrier",
		primary_coordinate = { 0, 0, 0 },
		status = "complete",
		owner = grid.neutral_team,
	}, grid)

	local result2 = hex_grid_mod.line_of_sight(grid, { -2, 0, 2 }, { 2, 0, -2 })
	assert(result2 == false, "has blockage: expected false")

	local result3 = hex_grid_mod.line_of_sight(grid, { 1, 0, -1 }, { 0, -1, 1 })
	assert(result3 == true, "expected true")

	entity_mod.new_entity({
		type = "barrier",
		primary_coordinate = { 1, -1, 0 },
		status = "complete",
		owner = grid.neutral_team,
	}, grid)

	local result4 = hex_grid_mod.line_of_sight(grid, { 1, 0, -1 }, { 0, -1, 1 })
	assert(result4 == false, "expected false")
	entity_mod.remove_entity(grid, barrier_at_origin)

	local result5 = hex_grid_mod.line_of_sight(grid, { 1, 0, -1 }, { 0, -1, 1 })
	assert(result5 == true, "expected true")

	entity_mod.new_entity({
		type = "barrier",
		primary_coordinate = { 3, 0, -3 },
		status = "complete",
		owner = grid.neutral_team,
	}, grid)

	entity_mod.new_entity({
		type = "scout",
		primary_coordinate = { 1, 0, -1 },
		status = "complete",
		owner = team1.id,
	}, grid)

	for _, cell in grid.cells do
		local coord = cell.coordinate
		if not hex_grid_mod.line_of_sight(grid, { 1, 0, -1 }, coord, team1.id) then
			cell.type = "rad_deposit"
		end
	end

	cleanup(grid)
end

function tests.damage_extractor()
	local grid = hex_grid_mod.new_grid_empty()
	grid.cells[hex_grid_mod.encode_coord { 0, 0, 0 }] = hex_grid_mod.empty_cell { 0, 0, 0 }
	local extractor = entity_mod.new_entity({
		type = "extractor",
		primary_coordinate = { 0, 0, 0 },
		status = "complete",
		owner = grid.neutral_team,
	}, grid)

	local autogenerated_wires = grid:query_entity({ primary_coordinate = { 0, 0, 0 }, type = "wires" })[1]

	damage_mod.destroy_entities(
		grid,
		damage_mod.apply_damage_on_cells(grid, { { 0, 0, 0 } }, {
			type = "flat",
			amount = 1,
		})
	)

	assert(extractor.health == extractor.max_health - 1, "extractor was not damaged")

	damage_mod.destroy_entities(
		grid,
		damage_mod.apply_damage_on_cells(grid, { { 0, 0, 0 } }, {
			type = "flat",
			amount = math.huge,
		})
	)

	assert(extractor.is_destroyed, "extractor was not destroyed")
	assert(autogenerated_wires.is_destroyed, "autogenerated wires was not destroyed")
	cleanup(grid)
end

function tests.capture_extractor()
	local grid = hex_grid_mod.new_grid_from_extents {
		{ min = -1, max = 1 },
		{ min = -1, max = 1 },
		{ min = -1, max = 1 },
	}
	local team1 = grid:new_team({}, { type = "color3", color = Color3.new(1, 0.392156, 0.392156) })
	local extractor = entity_mod.new_entity({
		type = "extractor",
		primary_coordinate = { 0, 0, 0 },
		status = "complete",
		owner = grid.neutral_team,
	}, grid)

	local infinite_source = entity_mod.new_entity({
		type = "infinite_source",
		status = "complete",
		primary_coordinate = { -1, 1, 0 },
		owner = team1.id,
	}, grid)

	local wires = entity_mod.new_entity({
		type = "wires",
		primary_coordinate = { 0, 0, 0 },
		status = "blueprint",
		owner = team1.id,
	}, grid)

	action_phase_mod.run_action_phase(grid)
	assert(extractor.owner == team1.id, "extractor was not captured")

	cleanup(grid)
end

function tests.wire_blueprint_builds()
	local grid = hex_grid_mod.new_grid_from_extents {
		{ min = -1, max = 1 },
		{ min = -1, max = 1 },
		{ min = -1, max = 1 },
	}
	local team1 = grid:new_team()

	local infinite_source = entity_mod.new_entity({
		type = "infinite_source",
		status = "complete",
		primary_coordinate = { 0, 0, 0 },
		owner = team1.id,
	}, grid)

	local wires = entity_mod.new_entity({
		type = "wires",
		status = "blueprint",
		primary_coordinate = { -1, 0, 1 },
		owner = team1.id,
	}, grid)

	action_phase_mod.run_action_phase(grid)

	assert(wires.status == "complete", "blueprint was not completed")
end

function tests.stockpile_blueprint_builds()
	local grid = hex_grid_mod.new_grid_from_extents {
		{ min = -1, max = 1 },
		{ min = -1, max = 1 },
		{ min = -1, max = 1 },
	}
	local team1 = grid:new_team()

	local infinite_source = entity_mod.new_entity({
		type = "infinite_source",
		status = "complete",
		primary_coordinate = { 0, 0, 0 },
		owner = team1.id,
	}, grid)
	local extractor = entity_mod.new_entity({
		type = "extractor",
		status = "blueprint",
		primary_coordinate = { -1, 0, 1 },
		owner = team1.id,
	}, grid)

	action_phase_mod.run_action_phase(grid)
	assert(extractor.status == "scaffold", "extractor blueprint did not become scaffold")

	action_phase_mod.run_action_phase(grid)

	assert((extractor :: any).status == "complete", "extractor scaffold was not completed")

	cleanup(grid)
end

function tests.deconstruct_stockpile()
	local grid = presets.testing_map()
	local stockpile = (grid:query_entity { type = "stockpile" })[1]

	table.insert(stockpile.queued_decisions, {
		type = "deconstruct",
		entity_id = stockpile.id,
	})

	action_phase_mod.run_action_phase(grid)

	assert(#(grid:query_entity { type = "stockpile" }) == 0, "stockpile is not destroyed by deconstruction")

	cleanup(grid)
end

function tests.deposit_different_items_in_vault()
	local grid = hex_grid_mod.new_grid_from_extents {
		{ min = -3, max = 3 },
		{ min = -3, max = 3 },
		{ min = -3, max = 3 },
	}
	local team1 = grid:new_team({}, { type = "color3", color = Color3.new(1, 0.392156, 0.392156) })
	local vault = entity_mod.new_entity({
		type = "vault",
		status = "complete",
		primary_coordinate = { 0, 0, 0 },
		owner = team1.id,
	}, grid)
	local bar_extractor = entity_mod.new_entity({
		type = "extractor",
		status = "complete",
		primary_coordinate = { 1, 0, -1 },
		owner = team1.id,
	}, grid)
	local rad_extractor = entity_mod.new_entity({
		type = "extractor",
		status = "complete",
		primary_coordinate = { -1, 0, 1 },
		owner = team1.id,
	}, grid)
	local generator = entity_mod.new_entity({
		type = "generator",
		status = "complete",
		primary_coordinate = { 0, 1, -1 },
		owner = team1.id,
	}, grid)
	grid:get_cell({ 1, 0, -1 }).type = "bar_deposit"
	grid:get_cell({ -1, 0, 1 }).type = "rad_deposit"

	action_phase_mod.run_action_phase(grid)

	cleanup(grid)
end

function tests.deconstruct_building_preserves_wires()
	local grid = hex_grid_mod.new_grid_from_extents {
		{ min = -1, max = 1 },
		{ min = -1, max = 1 },
		{ min = -1, max = 1 },
	}
	local team1 = grid:new_team({}, { type = "color3", color = Color3.new(1, 0.392156, 0.392156) })
	local scout = entity_mod.new_entity({
		type = "scout",
		status = "complete",
		primary_coordinate = { -1, 1, 0 },
		owner = team1.id,
	}, grid)
	assert(#grid:query_entity { type = "wires" } == 1, "wires not generated")
	table.insert(scout.queued_decisions, {
		type = "deconstruct",
		entity_id = scout.id,
	})
	action_phase_mod.run_action_phase(grid)
	assert(#grid:query_entity { type = "wires" } == 1, "wires not preserved")

	cleanup(grid)
end

function tests.scout_attack_each_other()
	local magic = 3
	local grid = hex_grid_mod.new_grid_from_extents {
		{ min = -magic, max = magic },
		{ min = -magic, max = magic },
		{ min = -magic, max = magic },
	}
	local team1 = grid:new_team({}, { type = "color3", color = Color3.new(1, 0.392156, 0.392156) })
	local team2 = grid:new_team({}, { type = "color3", color = Color3.new(0.301960, 0.403921, 1) })

	entity_mod.new_entity({
		type = "infinite_source",
		status = "complete",
		primary_coordinate = { -2, 2, 0 },
		owner = team1.id,
	}, grid)
	local scout = entity_mod.new_entity({
		type = "scout",
		status = "complete",
		primary_coordinate = { -1, 1, 0 },
		owner = team1.id,
	}, grid)
	entity_mod.new_entity({
		type = "infinite_source",
		status = "complete",
		primary_coordinate = { 2, -2, 0 },
		owner = team2.id,
	}, grid)
	local scout2 = entity_mod.new_entity({
		type = "scout",
		status = "complete",
		primary_coordinate = { 1, -1, 0 },
		owner = team2.id,
	}, grid)

	table.insert(scout.queued_decisions, {
		type = "ability",
		ability_type = "scout_attack",
		coordinate = { 1, -1, 0 },
		entity_id = scout.id,
	})

	action_phase_mod.run_action_phase(grid)

	assert(scout2.health == scout2.max_health - 1, "Scout 2 should have been damaged")

	-- reset scout health to full
	scout2.health = scout2.max_health

	for i = 1, 3 do
		table.insert(scout.queued_decisions, {
			type = "ability",
			ability_type = "scout_attack",
			coordinate = { 1, -1, 0 },
			entity_id = scout.id,
		})
		table.insert(scout2.queued_decisions, {
			type = "ability",
			ability_type = "scout_attack",
			coordinate = { -1, 1, 0 },
			entity_id = scout2.id,
		})
		action_phase_mod.run_action_phase(grid)
	end

	assert(scout.is_destroyed, "scout 1 should have been destroyed")
	assert(scout2.is_destroyed, "scout 2 should have been destroyed")

	cleanup(grid)
end

function tests.archive_grid()
	local grid = presets.my_map()
	local compressed = archive.compress_grid(grid)
	local original = HttpService:JSONEncode(grid)
	local decompressed = archive.decompress_grid(compressed)

	cleanup(grid)
end

return tests
