-- lobby types
export type Room = {
	id: string,
	teams: { [string]: { name: string, color: Color3, is_spectator_team: boolean? } },
	players: {
		-- tostring(Player.UserId)
		[string]: {
			team: string,
		},
	},
	map: string,
	starting_at: number?,
}

--- {x, y, z} where x,y,z: number and x+y+z = 0 <br/>
--- The z component can be derived but exists for completeness
export type CubicCoordinate = { number }
export type EncodedCoordinate = string

export type Signal<T> = {
	listen: (listener: (message: T) -> ()) -> (),
	send: (message: T) -> (),
	wait: () -> T,
	-- unlisten: (listener: (message: T) -> ()) -> (),
	destroy: () -> (),
}

export type Item = "vit" | "rad" | "pow" | "bar" | "tar" | "dew" | "dye" | "tek"

export type Inventory = {
	filter: Filter,
	-- true if all items are of the same type
	homogeneous: boolean,
	items: { Item },
	capacity: number,
}

export type Filter = {
	type: "whitelist" | "blacklist",
	items: { [Item]: boolean },
}

export type Recipe = {
	-- id: string,
	input_power: number,
	input_items: { [Item]: number },
	output_items: { Item },
	time: number,
	requires_research: { ResearchId }?,
}

export type ResearchId = string

export type ResearchState = {
	cost: { [Item]: number },
	cost_is_paid: boolean,
	time: number,
	progress: number,
	description: string,
	name: string,
	id: string,
	icon: Icon,
	coord: CubicCoordinate,
	status: "incomplete" | "researching" | "complete",

	precondition: (world: World, entity: Entity) -> boolean,
}

export type Researches = {
	queue: { ResearchId },
	states: {
		[string]: ResearchState,
	},
}

export type EffectType = "shield"

export type Effect = { is_destroyed: boolean?, duration: number? } & ({
	type: "shield",
	health: number,
} | {
	type: "infected",
} | {
	type: "infected_immune",
})

export type AnimationState = {
	type: "idle",
	step: number,
}

export type Entity = {
	active: boolean?,

	type: string,
	coordinates: { CubicCoordinate },
	primary_coordinate: CubicCoordinate,
	id: string,
	-- 0 - 5
	rotation: number,
	health: number,
	max_health: number,
	inventory: Inventory?,

	effects: { Effect },

	-- factory only
	current_recipe: string?,

	-- proxy only
	disguise: EntityId?,

	-- Whether this building's primary abilities are enabled
	enabled: boolean?,

	-- for heart and extractor
	should_output: number?,
	--- extractor only
	deposit: CellType?,

	-- entities enter decay when there is no longer a heart
	decay: number?,
	is_decaying: boolean?,
	decayable: boolean?,

	-- laboratory only
	researches: Researches?,

	-- Witness only
	charges: number?,

	-- An entity in blueprint phase
	cost: { [Item]: number },
	cost_fulfilled: { [Item]: number },

	-- for vertex so that vertex generated by a building cannot get abused for free vertex
	autogenerated: boolean?,

	status: "blueprint" | "scaffold" | "complete",
	is_destroyed: boolean?,
	build_time: number,

	owner: TeamId,
	queued_decisions: { Decision },

	-- for clients: .always_visible or .always_visible_for[team_id]
	always_visible: boolean?,
	server_data: {
		is_disguise_of: EntityId?,
		-- whether this entity is always visible regardless of whether the cell it is on is visible
		always_visible: boolean?,
		-- whether this entity is always visible for a specific team
		always_visible_for: { [TeamId]: boolean? },
		-- timestamp of when it was first requested to be constructed
		requested_at: number,

		will_die: { death_type: string },
	},
}

export type EntityId = string

export type ExtentsDim = { min: number, max: number }

export type Extents = { ExtentsDim }

export type InstanceMap<T> = { [T]: PVInstance }

export type CellType = "basic" | "bar_deposit" | "tar_deposit" | "vit_deposit" | "rad_deposit" | "portal"

type Portal = {
	group: { CubicCoordinate },
	open: boolean,
	steps: number,
	open_time: number,
	close_time: number,
}

export type CellTeamVisibility = {
	-- visible by virtue of having an entity right next to this cell
	contact: boolean?,
	-- visible by virtue of this team having fog disabled
	fogless: boolean?,
	-- visible by virtue of this cell being a portal and a connected portal being occupied by the team
	portal: boolean?,
	-- illuminated by scout, or (later on) torch
	illumination: boolean?,

	-- set by compute_visibility so action_phase can generate a minimal list of entity updates
	changed_to_true: boolean?,
}

export type HexCell = {
	type: CellType,
	entities: { [EntityId]: boolean },
	coordinate: CubicCoordinate,

	owner: TeamId?,

	-- client only property created in server.serialize.serialize_cell_for_team
	visible_for_team: boolean?,
	buildable_for_team: boolean?,

	portal: Portal?,

	influences: {
		[EntityId]: boolean,
	},
	server_data: {
		-- a presence is imposed by an enemy team, and prevents a player from building on that cell
		presence: {
			[TeamId]: boolean,
		},
		visibility: {
			[TeamId]: CellTeamVisibility,
		},
	},
}

export type TeamColor = {
	type: "color3",
	color: Color3,
} | {
	type: "color_sequence",
	color_sequence: ColorSequence,
}

export type TeamId = number
export type CoalitionId = number

export type CoalitionData = {
	name: string,
	id: CoalitionId,
	teams: { TeamId },
}

export type PlayerId = number
export type TeamData = {
	id: TeamId,
	name: string,
	color: TeamColor,
	players: { PlayerId },
	leader: PlayerId?,
	-- whether the game should automatically put players on this team
	is_player_team: boolean,
	-- spectator teams cannot interact with the game
	is_spectator_team: boolean?,

	server_data: {
		-- creative mode (todo)
		creative: boolean,
		-- "normal" is fog of war
		-- "fogless" disables cell-level fog of war but not entity-level (like phony)
		-- "perfect" is admin-level visibility
		visibility: "normal" | "fogless" | "perfect",
	},
	-- is_ai: boolean -- not confident i am capable of implementing ai
}

export type Decision = {
	type: "ability",
	ability_type: string,
	entity_id: EntityId,
	coordinate: CubicCoordinate,
} | {
	type: "construct",
	entity_type: string,
	coordinate: CubicCoordinate,
	rotation: number,
} | {
	type: "deconstruct",
	entity_id: EntityId,
} | {
	type: "rotate_entity",
	entity_id: EntityId,
	rotation: number,
}

export type Interaction = Decision | {
	type: "add_research",
	entity_id: EntityId,
	research_id: ResearchId,
} | {
	type: "cancel_decision",
	entity_id: EntityId,
	decision_type: string,
} | {
	type: "quest_advance",
	quest_id: string,
} | {
	type: "quest_select_choice",
	quest_id: string,
	choice_id: string,
} | {
	type: "remove_research",
	entity_id: EntityId,
	research_id: ResearchId,
} | {
	type: "set_entity_enabled",
	enabled: boolean,
	entity_id: EntityId,
} | {
	type: "set_inventory_filter",
	entity_id: EntityId,
	filter: Filter,
} | {
	type: "set_recipe",
	recipe_id: string,
	entity_id: EntityId,
} | {
	type: "skip",
} | {
	type: "tutorial_report_selection",
	selected: { CubicCoordinate },
}

export type Damage = {
	from: EntityId?,
	damage_type: ("physical" | "healing")?,
	amount: number,
	-- Whether this damage ignores shields
	-- Note piercing still respects layered entities (building above vertex)
	piercing: boolean?,
	-- Whether this damage can kill the entity
	nonlethal: boolean?,
	-- Whether this damage can affect friendly entities
	friendly_fire: boolean?,
}

export type DamageResult = {
		-- target
		amount: number,
		-- whether the damage killed this entity
		lethal: boolean,
	}


type TeamTarget = "everyone" | { TeamId }

export type Icon = {
	type: "image",
	image: string,
} | {
	type: "model",
	model: string,
} | {
	type: "none",
} | {
	type: "text",
	text: string,
} | nil

-- A message from Server to Client about the state of the game
export type WorldUpdate =
	-- handles add, update, and destruction
	{ type: "ability", ability_type: string, entity_id: EntityId, coordinate: CubicCoordinate } | { type: "cells", cells: { [EncodedCoordinate]: HexCell }, target: TeamTarget } | {
		type: "cell_update",
		cell: HexCell,
		target: TeamTarget,
	} | { type: "entity_created", entity_id: EntityId, target: TeamTarget } | { type: "entity_update", entity: Entity, target: TeamTarget } | (EntityEvent & { type: "entity_event", target: TeamTarget }) | {
		type: "exchange",
		input_items: { [Item]: number }?,
		input_power: number?,
		output_items: { Item }?,
		output_power: number?,
	} | {
		type: "quest_update",
		quest: Quest,
	} | {
		type: "teams",
		teams: { [TeamId]: TeamData },
		coalitions: { [CoalitionId]: CoalitionData },
	} | {
		type: "turn",
		turn: number,
		highest_turn: number,
	} | {
		type: "turn_completed",
	} | {
		type: "turn_skipped",
	} | {
		type: "turn_skips",
		current_skips: number,
		needed_skips: number,
	} | {
		type: "turn_timer",
		turn_start_time: number,
		turn_end_time: number,
	}

export type TurnSchedule = {
	end_time: number,
	get_end_time: () -> number,
	loop_thread: thread,
	now: number?,
	run_turn: () -> (),
	running: boolean,
	start_time: number,
	start_time_sync: number,
	turn_ran_signal: Signal<nil>,
	wait_thread: thread,
}

export type EntityConfiguration = {
	type: string,
	init: ((self: Entity, world: World) -> ())?,
	name: string,
	description: string,
	max_health: number,
	buildable: boolean,
	build_time: number,
	abilities: {
		[string]: { -- attack ability
			range: number,
			cost: { [Item]: number },
			damage: Damage,
		},
	},
	can_disable: boolean,
	incorporeal: true?,

	required_research: { ResearchId }?,

	-- extractor only
	cycles_to_output: number?,

	-- stockpile only
	inventory_capacity: number?,

	power_input: number?,
	output_power: number?,

	range: number?,

	-- list of offsets in addition to entity.primary_coordinate
	offsets: { CubicCoordinate },
	layer: number,
	cost: { [Item]: number },

	-- factory only
	recipes: { Recipe }?,
}

export type GlobalConfiguration = {
	decaying_enabled: boolean,
}

export type EntityEvent = {
	event_type: "consumed_items",
	items: { [Item]: number },
	entity_id: EntityId,
} | {
	event_type: "created",
	entity_id: EntityId,
} | {
	event_type: "destroy",
	entity_id: EntityId,
	death_type: "deconstruct" | "killed" | "used" | "other",
	damage_result: DamageResult?,
	damage: Damage?,
} | {
	event_type: "produced_items",
	items: { [Item]: number },
	entity_id: EntityId,
} | {
	event_type: "research_completed",
	entity_id: EntityId,
	research_id: ResearchId,
} | {
	event_type: "status_changed",
	entity_id: EntityId,
} | {
	event_type: "took_damage",
	damage_result: DamageResult,
	damage: Damage,
	entity_id: EntityId,
} | {
	event_type: "update",
	entity_id: EntityId,
} | {
	event_type: "promoted",
	entity_id: EntityId,
}

export type EntityAction =
	-- attempt to fill as much of the blueprint as possible from inventories and overflow
	-- if enough items are fulfilled, the blueprint promotes to scaffold. if the build time is 0, it automatically promotes to complete
	{
		type: "try_promote_blueprint",
		entity_id: EntityId,
	}
	-- advances scaffold by 1 turn
	-- if build time is 0, it is promoted to complete
	| {
		type: "try_promote_scaffold",
		entity_id: EntityId,
	}
	| {
		type: "exchange",
		input_items: { [Item]: number }?,
		input_power: number?,
		output_items: { Item }?,
		output_power: number?,
		on_success: (world: World) -> (),
	}
	| {
		type: "run_late",
		entity_id: EntityId,
		run: (world: World, entity: Entity) -> (),
	}
	| (EntityEvent & { type: "entity_event" })
	| Decision

export type System = {
	entities: { [EntityId]: boolean },
	cells: { [EncodedCoordinate]: boolean },
}

export type World = {
	-- instances are always nil on the server, while always a table on the client
	entity_instance_map: InstanceMap<EntityId>,
	entities: { [EntityId]: Entity },
	world_update_signal: Signal<{ WorldUpdate }>,
	instance_entity_map: { [Instance]: EntityId },
	-- ngl i forgot why I used EncodedCoordinate instead of CubicCoordinate
	instance_cell_map: { [Instance]: EncodedCoordinate },
	cell_instance_map: InstanceMap<EncodedCoordinate>,
	cells: { [EncodedCoordinate]: HexCell },

	cell_instance_root: Folder?,
	entity_instance_root: Folder?,

	entity_configurations: { [string]: EntityConfiguration },
	global_configuration: GlobalConfiguration,
	--
	get_cell: (self: World, coordinate: CubicCoordinate) -> HexCell?,
	-- returns table of entities that fit the criteria
	query_entity: (self: World, props: any) -> { Entity },
	add_update: (self: World, update: WorldUpdate) -> (),
	--
	active_entities: (self: World) -> { [EntityId]: Entity },

	-- get_team_coalition: (self: World, team: TeamId) -> CoalitionData,

	-- server only
	action_queue: { EntityAction },

	coalitions: { CoalitionData },
	teams: { TeamData },

	neutral_team: TeamId,
	spectator_team: TeamId,

	systems: { System },

	-- player teams can grant or revoke visibility to spectators
	-- use userid so visibility is preserved even after the spectator leaves
	spectator_visibilities: { [number]: {
		[TeamId]: {
			visible: boolean,
			revocable: boolean,
		},
	} },

	updates_buffer: { WorldUpdate },

	turn_schedule: TurnSchedule?,

	turn: number,
	highest_turn: number,

	-- userids
	skipped: { number },

	-- read only for client
	current_skips: number,
	needed_skips: number,

	-- Amount of time between each turn is calculated as speed_multiplier * num_teams + speed_base
	speed_multiplier: number,
	speed_base: number,

	quests: { [string]: Quest },

	-- client only
	animation_states: { [EntityId]: AnimationState }?,
}

export type PartialWorld = {
	cells: { [EncodedCoordinate]: HexCell },
	coalitions: { CoalitionData },
	teams: { TeamData },
	turn: number,
	highest_turn: number,
	entities: { [EntityId]: Entity },
	turn_schedule: {
		start_time: number,
		end_time: number,
		running: boolean,
	}?,
	current_skips: number,
	needed_skips: number,
	entity_configurations: { [string]: EntityConfiguration },
	global_configuration: GlobalConfiguration,
	neutral_team: TeamId,
	spectator_team: TeamId,
	quests: { [string]: Quest },
	systems: { System },
}

-- Questing types
export type QuestEffect = {
	type: "highlight_cell",
	coordinate: CubicCoordinate,
} | {
	type: "highlight_build_button",
} | {
	type: "highlight_buildable",
	entity_type: string,
} | {
	type: "whitelist_buildable",
	entities: {
		[string]: true,
	},
}

export type QuestStage = {
	-- list of messages for this stage
	messages: { string }?,
	-- id of the next stage
	next: string?,
	-- list of effects/restrictions for the client for this stage
	effects: { QuestEffect }?,
	-- whether the client can click to advance
	can_advance: boolean?,
	choices: {
		{
			id: string,
			text: string,
		}
	}?,
}

export type ServerQuestStageBehavior = {
	progression_requisite: ((Quest, World) -> boolean)?,
	stage_start: ((Quest, World) -> ())?,
	choice_selected: ((Quest, World, string) -> ())?,
}

export type Quest = {
	id: string,
	title: string,
	current_stage: string,
	-- client only
	current_stage_data: QuestStage,
	-- server only
	stages_data: { [string]: QuestStage },
	stages_behavior: { [string]: ServerQuestStageBehavior },
	quest_update_signal: Signal<Quest>,
	-- tutorial only, keeps track of which cells the player is selecting
	tutorial_player_selection: { [Player]: { CubicCoordinate } }?,
	details: any,
}

return {}
